-- Add brand_summary column to brand_analysis_projects table
-- This stores the generated brand profile summary to avoid regenerating it every time

ALTER TABLE brand_analysis_projects
ADD COLUMN IF NOT EXISTS brand_summary JSONB DEFAULT NULL,
ADD COLUMN IF NOT EXISTS brand_summary_updated_at TIMESTAMPTZ DEFAULT NULL;

-- Add index for faster queries
CREATE INDEX IF NOT EXISTS idx_brand_analysis_projects_brand_summary_updated_at 
ON brand_analysis_projects(brand_summary_updated_at DESC);

-- Comment
COMMENT ON COLUMN brand_analysis_projects.brand_summary IS 'Stored brand profile summary (overview, industry, business_model, etc.) generated by brand-analysis-summary edge function';
COMMENT ON COLUMN brand_analysis_projects.brand_summary_updated_at IS 'Timestamp when brand_summary was last generated/updated';
