"use client";

import { useRef, useState, useCallback } from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import toast from "react-hot-toast";

interface ExportOptions {
  reportTitle: string;
  domain: string;
  fileName: string;
  prepareExport?: () => void | Promise<void>;
  cleanupExport?: () => void;
}

async function loadLogo(): Promise<string | null> {
  try {
    const img = document.createElement("img") as HTMLImageElement;
    img.crossOrigin = "anonymous";
    return await new Promise<string | null>((resolve) => {
      const t = setTimeout(() => resolve(null), 4000);
      img.onload = () => {
        clearTimeout(t);
        try {
          const c = document.createElement("canvas");
          c.width = 400;
          c.height = 400;
          const ctx = c.getContext("2d");
          if (!ctx) { resolve(null); return; }
          ctx.drawImage(img, 0, 0, 400, 400);
          resolve(c.toDataURL("image/png", 0.95));
        } catch { resolve(null); }
      };
      img.onerror = () => { clearTimeout(t); resolve(null); };
      img.src = "/logo.png";
    });
  } catch {
    return null;
  }
}

const PURPLE_DEEP = { r: 79, g: 25, b: 143 };
const PURPLE_BRIGHT = { r: 124, g: 58, b: 237 };
const PURPLE_LIGHT = { r: 167, g: 139, b: 250 };
const GOLD = { r: 245, g: 158, b: 11 };
const WHITE = { r: 255, g: 255, b: 255 };

export function useReportPDFExport() {
  const reportRef = useRef<HTMLDivElement>(null);
  const [exportingPDF, setExportingPDF] = useState(false);

  const handleExportPDF = useCallback(async (opts: ExportOptions) => {
    if (!reportRef.current) return;
    setExportingPDF(true);
    toast.loading("Generating PDF report…", { id: "export-pdf" });

    try {
      await opts.prepareExport?.();

      const doc = new jsPDF("p", "mm", "a4");
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 12;
      const contentWidth = pageWidth - 2 * margin;
      const HEADER_H = 22;
      const FOOTER_H = 14;
      const contentTop = HEADER_H + 3;
      const contentBottom = pageHeight - FOOTER_H;
      const sectionGap = 4;
      const SECTION_LABEL_H = 12;

      const logoData = await loadLogo();

      const addHeader = () => {
        doc.setFillColor(PURPLE_DEEP.r, PURPLE_DEEP.g, PURPLE_DEEP.b);
        doc.rect(0, 0, pageWidth, HEADER_H - 2, "F");
        doc.setFillColor(PURPLE_BRIGHT.r, PURPLE_BRIGHT.g, PURPLE_BRIGHT.b);
        doc.rect(0, 0, pageWidth, 2, "F");
        if (logoData) {
          try { doc.addImage(logoData, "PNG", margin, 4.5, 11, 11); } catch { /* skip */ }
        }
        const tx = logoData ? margin + 14 : margin;
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(WHITE.r, WHITE.g, WHITE.b);
        doc.text("GEORepute.ai", tx, 10.5);
        doc.setFontSize(6.5);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
        doc.text("AI Visibility Intelligence Platform", tx, 15);
        doc.setFontSize(8);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(WHITE.r, WHITE.g, WHITE.b);
        doc.text(opts.reportTitle.toUpperCase(), pageWidth - margin, 9.5, { align: "right" });
        doc.setFontSize(6.5);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
        doc.text(opts.domain, pageWidth - margin, 14, { align: "right" });
        doc.setFillColor(GOLD.r, GOLD.g, GOLD.b);
        doc.rect(0, HEADER_H - 2, pageWidth, 0.8, "F");
      };

      const addFooter = (pg: number, total: number) => {
        const fy = pageHeight - FOOTER_H + 2;
        doc.setDrawColor(200, 200, 200);
        doc.setLineWidth(0.3);
        doc.line(margin, fy, pageWidth - margin, fy);
        doc.setFontSize(6.5);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(140, 140, 140);
        doc.text("Confidential \u2014 Generated by GEORepute.ai", margin, fy + 4.5);
        doc.text(`Page ${pg} of ${total}`, pageWidth / 2, fy + 4.5, { align: "center" });
        doc.text(
          new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }),
          pageWidth - margin, fy + 4.5, { align: "right" }
        );
        doc.setFillColor(PURPLE_DEEP.r, PURPLE_DEEP.g, PURPLE_DEEP.b);
        doc.rect(0, pageHeight - 3, pageWidth, 3, "F");
        doc.setFillColor(GOLD.r, GOLD.g, GOLD.b);
        doc.rect(0, pageHeight - 3, pageWidth, 0.5, "F");
      };

      const addSectionLabel = (name: string) => {
        if (yPos + SECTION_LABEL_H > contentBottom) {
          doc.addPage();
          addHeader();
          yPos = contentTop;
        }
        doc.setFillColor(PURPLE_BRIGHT.r, PURPLE_BRIGHT.g, PURPLE_BRIGHT.b);
        doc.roundedRect(margin, yPos, contentWidth, 10, 1.5, 1.5, "F");
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(WHITE.r, WHITE.g, WHITE.b);
        doc.text(name, margin + 4, yPos + 7);
        yPos += SECTION_LABEL_H;
      };

      addHeader();
      let yPos = contentTop;

      const sections = reportRef.current!.querySelectorAll("[data-pdf-section]");

      for (let i = 0; i < sections.length; i++) {
        const el = sections[i] as HTMLElement;

        const sectionName = el.getAttribute("data-pdf-section-name");
        if (sectionName) addSectionLabel(sectionName);

        const scrollables = el.querySelectorAll<HTMLElement>(
          "[class*='overflow-y-auto'], [class*='overflow-x-auto'], [class*='max-h-']"
        );
        const savedStyles: { el: HTMLElement; overflow: string; maxHeight: string }[] = [];
        scrollables.forEach((s) => {
          savedStyles.push({ el: s, overflow: s.style.overflow, maxHeight: s.style.maxHeight });
          s.style.overflow = "visible";
          s.style.maxHeight = "none";
        });

        const canvas = await html2canvas(el, {
          scale: 2,
          useCORS: true,
          allowTaint: true,
          backgroundColor: "#ffffff",
          logging: false,
          imageTimeout: 0,
        });

        savedStyles.forEach(({ el: s, overflow, maxHeight }) => {
          s.style.overflow = overflow;
          s.style.maxHeight = maxHeight;
        });

        if (canvas.width === 0 || canvas.height === 0) continue;

        let imgData: string;
        try {
          imgData = canvas.toDataURL("image/jpeg", 0.92);
          if (!imgData || !imgData.startsWith("data:image/")) continue;
        } catch {
          continue;
        }

        const imgWidth = contentWidth;
        const imgHeight = (canvas.height * contentWidth) / canvas.width;
        const imgFormat = "JPEG";

        const addImageSafe = (data: string, w: number, h: number) => {
          try {
            doc.addImage(data, imgFormat, margin, yPos, w, h);
            return true;
          } catch (err) {
            console.warn("PDF addImage failed for section, skipping:", err);
            return false;
          }
        };

        if (yPos + imgHeight > contentBottom && yPos > contentTop + 2) {
          doc.addPage();
          addHeader();
          yPos = contentTop;
        }

        const maxH = contentBottom - contentTop;
        if (imgHeight > maxH) {
          const pxPerMm = canvas.width / imgWidth;
          let remaining = imgHeight;
          let srcY = 0;
          while (remaining > 0) {
            const avail = contentBottom - yPos;
            const sliceH = Math.min(remaining, avail);
            const slicePx = Math.max(1, Math.ceil(sliceH * pxPerMm));
            const sc = document.createElement("canvas");
            sc.width = canvas.width;
            sc.height = slicePx;
            const ctx = sc.getContext("2d");
            if (ctx) {
              ctx.drawImage(canvas, 0, srcY, canvas.width, slicePx, 0, 0, canvas.width, slicePx);
              let sliceData: string;
              try {
                sliceData = sc.toDataURL("image/jpeg", 0.92);
                if (sliceData?.startsWith("data:image/") && addImageSafe(sliceData, imgWidth, sliceH)) {
                  yPos += sliceH;
                }
              } catch { /* skip slice */ }
            }
            srcY += slicePx;
            remaining -= sliceH;
            if (remaining > 0) {
              doc.addPage();
              addHeader();
              yPos = contentTop;
            }
          }
          yPos += sectionGap;
        } else {
          if (addImageSafe(imgData, imgWidth, imgHeight)) {
            yPos += imgHeight + sectionGap;
          }
        }
      }

      const totalPages = doc.getNumberOfPages();
      for (let p = 1; p <= totalPages; p++) {
        doc.setPage(p);
        addFooter(p, totalPages);
      }

      doc.save(opts.fileName);
      toast.success("PDF exported successfully!", { id: "export-pdf" });
    } catch (error) {
      console.error("PDF export error:", error);
      toast.error("Failed to export PDF. Please try again.", { id: "export-pdf" });
    } finally {
      opts.cleanupExport?.();
      setExportingPDF(false);
    }
  }, []);

  return { reportRef, exportingPDF, handleExportPDF };
}
