/**
 * Pre-translated strings for video report prompts.
 * Using actual translated text in the prompt ensures the video model renders content in the selected language.
 * Fallback: languages not in map use English + strong "translate all" instruction.
 */

export type VideoLangCode =
  | "en" | "ar" | "zh" | "da" | "nl" | "fi" | "fr" | "de" | "he" | "hi" | "id" | "it"
  | "ja" | "ko" | "no" | "pl" | "pt" | "ru" | "es" | "sv" | "th" | "tr" | "ur" | "vi";

export const LANGUAGE_NAMES: Record<string, string> = {
  en: "English", "en-US": "English", "en-GB": "English",
  he: "Hebrew", ur: "Urdu", de: "German", fr: "French",
  es: "Spanish", it: "Italian", pt: "Portuguese", nl: "Dutch",
  ja: "Japanese", zh: "Chinese", pl: "Polish", ru: "Russian",
  ko: "Korean", ar: "Arabic", tr: "Turkish", hi: "Hindi",
  th: "Thai", vi: "Vietnamese", id: "Indonesian", sv: "Swedish",
  no: "Norwegian", da: "Danish", fi: "Finnish",
};

// ── Opportunity Blind Spots ─────────────────────────────────────────────────
export interface OppBlindSpotsStrings {
  title: string;
  tagline: string;
  revenueAtRisk: string;
  totalQueries: string;
  priorityGaps: string;
  avgCpc: string;
  topBlindSpotOpportunities: string;
  gapDistribution: string;
  neither: string;
  others: string;
  topValue: string;
  closing: string;
  fixGapsCta: string;
  demand: string;
  val: string;
}

// ── Market Share of Attention ───────────────────────────────────────────────
export interface MarketShareStrings {
  title: string;
  tagline: string;
  attentionScores: string;
  marketScore: string;
  aiMention: string;
  organic: string;
  defaultLeader: string;
  challenger: string;
  aiMentionsQueries: string;
  engineBreakdown: string;
  aiShareVsOrganic: string;
  closingDefaultLeader: string;
  closingChallenger: string;
}

// ── Strategic Blind Spots ────────────────────────────────────────────────────
export interface StrategicBlindSpotsStrings {
  title: string;
  tagline: string;
  whatAreWeIgnoring: string;
  ignored: string;
  score: string;
  aiBlind: string;
  urgent: string;
  topBlindSpots: string;
  priority: string;
  high: string;
  med: string;
  low: string;
  aiGap: string;
  ignores: string;
  mentions: string;
  closing: string;
  fixFirst: string;
  worstAiGap: string;
}

// ── AI Search Presence ──────────────────────────────────────────────────────
export interface AiSearchPresenceStrings {
  title: string;
  tagline: string;
  presenceMetrics: string;
  presenceScore: string;
  mentions: string;
  engines: string;
  sentiment: string;
  positive: string;
  negative: string;
  neutral: string;
  engineBreakdown: string;
  overallScore: string;
  best: string;
  worst: string;
  closingStrong: string;
  closingImprove: string;
}

// ── AI vs Google Gap ─────────────────────────────────────────────────────────
export interface AiVsGoogleGapStrings {
  title: string;
  tagline: string;
  visibilityGapReport: string;
  aiRisk: string;
  moderateGap: string;
  balanced: string;
  seoOpp: string;
  avgGapScore: string;
  totalQueries: string;
  topAiRiskQueries: string;
  bandSplit: string;
  seoOpportunity: string;
  closing: string;
}

// ── Geo Visibility Market Coverage ───────────────────────────────────────────
export interface GeoVisibilityStrings {
  title: string;
  tagline: string;
  coverageReport: string;
  regionsAnalyzed: string;
  covered: string;
  coverageGaps: string;
  avgVisibility: string;
  topPerformingRegions: string;
  coverage: string;
  gaps: string;
  regionsCovered: string;
  gapMarketsIdentified: string;
  focusClosing: string;
}

// ── Global Visibility Matrix ──────────────────────────────────────────────────
export interface GlobalVisibilityStrings {
  title: string;
  tagline: string;
  globalCoverage: string;
  strong: string;
  emerging: string;
  declining: string;
  absent: string;
  countriesAnalyzed: string;
  avgScore: string;
  topOpportunities: string;
  absentMarkets: string;
  closing: string;
}

// ── Global Visibility Matrix (Google Search tab) ─────────────────────────────────
export interface GlobalVisibilityGoogleStrings {
  title: string;
  tagline: string;
  googleSearchReport: string;
  totalClicks: string;
  totalImpressions: string;
  avgCtr: string;
  regionsAnalyzed: string;
  topByClicks: string;
  topByImpressions: string;
  closing: string;
}

// ── Translation maps (en = base; others override) ───────────────────────────

const OPP_BLIND_SPOTS: Record<VideoLangCode, OppBlindSpotsStrings> = {
  en: { title: "Opportunity Blind Spots", tagline: "Revenue opportunities invisible to Google and AI.", revenueAtRisk: "Revenue at Risk", totalQueries: "Total Queries", priorityGaps: "Priority Gaps", avgCpc: "Avg CPC", topBlindSpotOpportunities: "TOP BLIND SPOT OPPORTUNITIES", gapDistribution: "Gap Distribution", neither: "Neither", others: "Others", topValue: "Top Value", closing: "blind spots with", fixGapsCta: "Fix these gaps to capture both Google and AI traffic.", demand: "demand", val: "val" },
  es: { title: "Oportunidades y Puntos Ciegos", tagline: "Oportunidades de ingresos invisibles para Google y la IA.", revenueAtRisk: "Ingresos en Riesgo", totalQueries: "Consultas Totales", priorityGaps: "Brechas Prioritarias", avgCpc: "CPC Promedio", topBlindSpotOpportunities: "PRINCIPALES OPORTUNIDADES DE PUNTOS CIEGOS", gapDistribution: "Distribución de Brechas", neither: "Ninguno", others: "Otros", topValue: "Mayor Valor", closing: "puntos ciegos con", fixGapsCta: "Corrija estas brechas para capturar tráfico de Google y IA.", demand: "demanda", val: "valor" },
  fr: { title: "Opportunités et Angles Morts", tagline: "Opportunités de revenus invisibles pour Google et l'IA.", revenueAtRisk: "Revenus à Risque", totalQueries: "Requêtes Totales", priorityGaps: "Écarts Prioritaires", avgCpc: "CPC Moyen", topBlindSpotOpportunities: "PRINCIPALES OPPORTUNITÉS D'ANGLES MORTS", gapDistribution: "Distribution des Écarts", neither: "Aucun", others: "Autres", topValue: "Valeur Maximale", closing: "angles morts avec", fixGapsCta: "Comblez ces écarts pour capter le trafic Google et IA.", demand: "demande", val: "valeur" },
  de: { title: "Chancen und tote Winkel", tagline: "Umsatzchancen unsichtbar für Google und KI.", revenueAtRisk: "Umsatzrisiko", totalQueries: "Anfragen Gesamt", priorityGaps: "Prioritätslücken", avgCpc: "Ø CPC", topBlindSpotOpportunities: "TOP CHANCEN TOTER WINKEL", gapDistribution: "Lückenverteilung", neither: "Keins", others: "Andere", topValue: "Höchster Wert", closing: "tote Winkel mit", fixGapsCta: "Schließen Sie diese Lücken für Google- und KI-Traffic.", demand: "Nachfrage", val: "Wert" },
  zh: { title: "机会与盲点", tagline: "谷歌和AI看不见的收入机会。", revenueAtRisk: "收入风险", totalQueries: "总查询数", priorityGaps: "优先缺口", avgCpc: "平均CPC", topBlindSpotOpportunities: "主要盲点机会", gapDistribution: "缺口分布", neither: "两者皆无", others: "其他", topValue: "最高价值", closing: "个盲点，", fixGapsCta: "弥补这些缺口以获取谷歌和AI流量。", demand: "需求", val: "价值" },
  ja: { title: "機会と盲点", tagline: "GoogleとAIに見えない収益機会。", revenueAtRisk: "収益リスク", totalQueries: "総クエリ数", priorityGaps: "優先ギャップ", avgCpc: "平均CPC", topBlindSpotOpportunities: "主要な盲点機会", gapDistribution: "ギャップ分布", neither: "どちらもなし", others: "その他", topValue: "最高価値", closing: "個の盲点、", fixGapsCta: "これらのギャップを解消してGoogleとAIのトラフィックを獲得。", demand: "需要", val: "価値" },
  pt: { title: "Oportunidades e Pontos Cegos", tagline: "Oportunidades de receita invisíveis para Google e IA.", revenueAtRisk: "Receita em Risco", totalQueries: "Consultas Totais", priorityGaps: "Lacunas Prioritárias", avgCpc: "CPC Médio", topBlindSpotOpportunities: "PRINCIPAIS OPORTUNIDADES DE PONTOS CEGOS", gapDistribution: "Distribuição de Lacunas", neither: "Nenhum", others: "Outros", topValue: "Maior Valor", closing: "pontos cegos com", fixGapsCta: "Corrija essas lacunas para capturar tráfego do Google e IA.", demand: "demanda", val: "valor" },
  ar: { title: "الفرص والنقاط العمياء", tagline: "فرص إيرادات غير مرئية لـ Google والذكاء الاصطناعي.", revenueAtRisk: "الإيرادات المعرضة للخطر", totalQueries: "إجمالي الاستعلامات", priorityGaps: "الفجوات ذات الأولوية", avgCpc: "متوسط CPC", topBlindSpotOpportunities: "أهم فرص النقاط العمياء", gapDistribution: "توزيع الفجوات", neither: "لا شيء", others: "أخرى", topValue: "أعلى قيمة", closing: "نقاط عمياء مع", fixGapsCta: "أصلح هذه الفجوات لاستقطاب حركة Google والذكاء الاصطناعي.", demand: "الطلب", val: "القيمة" },
  he: { title: "הזדמנויות ונקודות עיוורון", tagline: "הזדמנויות הכנסה בלתי נראות ל-Google ול-AI.", revenueAtRisk: "הכנסה בסיכון", totalQueries: "סה״כ שאילתות", priorityGaps: "פערים בעדיפות", avgCpc: "CPC ממוצע", topBlindSpotOpportunities: "הזדמנויות עיקריות", gapDistribution: "התפלגות פערים", neither: "אף אחד", others: "אחרים", topValue: "ערך עליון", closing: "נקודות עיוורון עם", fixGapsCta: "תקן פערים אלה לתפיסת תעבורת Google ו-AI.", demand: "ביקוש", val: "ערך" },
  ru: { title: "Возможности и слепые зоны", tagline: "Доходные возможности, невидимые для Google и ИИ.", revenueAtRisk: "Риск дохода", totalQueries: "Всего запросов", priorityGaps: "Приоритетные пробелы", avgCpc: "Средний CPC", topBlindSpotOpportunities: "ОСНОВНЫЕ ВОЗМОЖНОСТИ", gapDistribution: "Распределение пробелов", neither: "Ни то, ни другое", others: "Другие", topValue: "Макс. ценность", closing: "слепых зон с", fixGapsCta: "Устраните эти пробелы для трафика Google и ИИ.", demand: "спрос", val: "ценность" },
  it: { title: "Opportunità e Punti Ciechi", tagline: "Opportunità di ricavi invisibili per Google e IA.", revenueAtRisk: "Ricavi a Rischio", totalQueries: "Query Totali", priorityGaps: "Lacune Prioritarie", avgCpc: "CPC Medio", topBlindSpotOpportunities: "PRINCIPALI OPPORTUNITÀ", gapDistribution: "Distribuzione Lacune", neither: "Nessuno", others: "Altri", topValue: "Valore Massimo", closing: "punti ciechi con", fixGapsCta: "Colmate queste lacune per catturare traffico Google e IA.", demand: "domanda", val: "valore" },
  nl: { title: "Kansen en blinde vlekken", tagline: "Omzetkansen onzichtbaar voor Google en AI.", revenueAtRisk: "Omzetrisico", totalQueries: "Totaal zoekopdrachten", priorityGaps: "Prioriteitshiaten", avgCpc: "Gem. CPC", topBlindSpotOpportunities: "TOP KANSEN", gapDistribution: "Hiaatverdeling", neither: "Geen", others: "Overige", topValue: "Hoogste waarde", closing: "blinde vlekken met", fixGapsCta: "Los deze hiaten op voor Google- en AI-verkeer.", demand: "vraag", val: "waarde" },
  pl: { title: "Szanse i martwe punkty", tagline: "Szanse przychodów niewidoczne dla Google i AI.", revenueAtRisk: "Ryzyko przychodów", totalQueries: "Łączne zapytania", priorityGaps: "Priorytetowe luki", avgCpc: "Śr. CPC", topBlindSpotOpportunities: "GŁÓWNE SZANSE", gapDistribution: "Rozkład luk", neither: "Żadne", others: "Inne", topValue: "Maks. wartość", closing: "martwych punktów z", fixGapsCta: "Uzupełnij te luki, aby zdobyć ruch z Google i AI.", demand: "popyt", val: "wartość" },
  ko: { title: "기회와 맹점", tagline: "Google과 AI에 보이지 않는 수익 기회.", revenueAtRisk: "수익 위험", totalQueries: "총 쿼리", priorityGaps: "우선 갭", avgCpc: "평균 CPC", topBlindSpotOpportunities: "주요 맹점 기회", gapDistribution: "갭 분포", neither: "둘 다 아님", others: "기타", topValue: "최고 가치", closing: "개 맹점, ", fixGapsCta: "이 갭을 해소하여 Google 및 AI 트래픽을 확보하세요.", demand: "수요", val: "가치" },
  tr: { title: "Fırsatlar ve Kör Noktalar", tagline: "Google ve yapay zeka için görünmeyen gelir fırsatları.", revenueAtRisk: "Gelir Riski", totalQueries: "Toplam Sorgu", priorityGaps: "Öncelikli Boşluklar", avgCpc: "Ort. CPC", topBlindSpotOpportunities: "ANA FIRSATLAR", gapDistribution: "Boşluk Dağılımı", neither: "Hiçbiri", others: "Diğerleri", topValue: "En Yüksek Değer", closing: "kör nokta, ", fixGapsCta: "Google ve yapay zeka trafiğini yakalamak için bu boşlukları kapatın.", demand: "talep", val: "değer" },
  hi: { title: "अवसर और अंध स्थान", tagline: "Google और AI के लिए अदृश्य राजस्व अवसर।", revenueAtRisk: "राजस्व जोखिम", totalQueries: "कुल क्वेरी", priorityGaps: "प्राथमिक अंतराल", avgCpc: "औसत CPC", topBlindSpotOpportunities: "शीर्ष अवसर", gapDistribution: "अंतराल वितरण", neither: "कोई नहीं", others: "अन्य", topValue: "शीर्ष मूल्य", closing: "अंध स्थान, ", fixGapsCta: "Google और AI ट्रैफिक पाने के लिए इन अंतरालों को भरें।", demand: "मांग", val: "मूल्य" },
  th: { title: "โอกาสและจุดบอด", tagline: "โอกาสรายได้ที่มองไม่เห็นสำหรับ Google และ AI", revenueAtRisk: "ความเสี่ยงรายได้", totalQueries: "คำค้นรวม", priorityGaps: "ช่องว่างสำคัญ", avgCpc: "CPC เฉลี่ย", topBlindSpotOpportunities: "โอกาสหลัก", gapDistribution: "การกระจายช่องว่าง", neither: "ไม่มี", others: "อื่นๆ", topValue: "มูลค่าสูงสุด", closing: "จุดบอด พร้อม", fixGapsCta: "แก้ไขช่องว่างเหล่านี้เพื่อดึงการเข้าชมจาก Google และ AI", demand: "ความต้องการ", val: "มูลค่า" },
  vi: { title: "Cơ hội và Điểm mù", tagline: "Cơ hội doanh thu vô hình với Google và AI.", revenueAtRisk: "Rủi ro doanh thu", totalQueries: "Tổng truy vấn", priorityGaps: "Khoảng trống ưu tiên", avgCpc: "CPC trung bình", topBlindSpotOpportunities: "CƠ HỘI CHÍNH", gapDistribution: "Phân bố khoảng trống", neither: "Không", others: "Khác", topValue: "Giá trị cao nhất", closing: "điểm mù với", fixGapsCta: "Khắc phục các khoảng trống này để thu hút lưu lượng Google và AI.", demand: "nhu cầu", val: "giá trị" },
  id: { title: "Peluang dan Titik Buta", tagline: "Peluang pendapatan tak terlihat untuk Google dan AI.", revenueAtRisk: "Risiko Pendapatan", totalQueries: "Total Kueri", priorityGaps: "Kesenjangan Prioritas", avgCpc: "CPC Rata-rata", topBlindSpotOpportunities: "PELUANG UTAMA", gapDistribution: "Distribusi Kesenjangan", neither: "Tidak ada", others: "Lainnya", topValue: "Nilai Tertinggi", closing: "titik buta dengan", fixGapsCta: "Perbaiki kesenjangan ini untuk menangkap lalu lintas Google dan AI.", demand: "permintaan", val: "nilai" },
  sv: { title: "Möjligheter och blinda fläckar", tagline: "Intäktsmöjligheter osynliga för Google och AI.", revenueAtRisk: "Intäktsrisk", totalQueries: "Totalt antal sökningar", priorityGaps: "Prioritetsluckor", avgCpc: "Snitt CPC", topBlindSpotOpportunities: "FRÄMSTA MÖJLIGHETER", gapDistribution: "Luckfördelning", neither: "Ingen", others: "Övriga", topValue: "Högsta värde", closing: "blinda fläckar med", fixGapsCta: "Åtgärda dessa luckor för att fånga Google- och AI-trafik.", demand: "efterfrågan", val: "värde" },
  no: { title: "Muligheter og blindsoner", tagline: "Inntektsmuligheter usynlige for Google og AI.", revenueAtRisk: "Inntektsrisiko", totalQueries: "Totalt antall søk", priorityGaps: "Prioritetshull", avgCpc: "Snitt CPC", topBlindSpotOpportunities: "VIKTIGSTE MULIGHETER", gapDistribution: "Hullfordeling", neither: "Ingen", others: "Andre", topValue: "Høyeste verdi", closing: "blindsoner med", fixGapsCta: "Lukk disse hullene for å fange Google- og AI-trafikk.", demand: "etterspørsel", val: "verdi" },
  da: { title: "Muligheder og blinde vinkler", tagline: "Indtægtsmuligheder usynlige for Google og AI.", revenueAtRisk: "Indtægtsrisiko", totalQueries: "Samlede forespørgsler", priorityGaps: "Prioritetshuller", avgCpc: "Gns. CPC", topBlindSpotOpportunities: "VIGTIGSTE MULIGHEDER", gapDistribution: "Hulfordeling", neither: "Ingen", others: "Andre", topValue: "Højeste værdi", closing: "blinde vinkler med", fixGapsCta: "Luk disse huller for at fange Google- og AI-trafik.", demand: "efterspørgsel", val: "værdi" },
  fi: { title: "Mahdollisuudet ja sokeat kohdat", tagline: "Tulomahdollisuudet näkymättöminä Googlelle ja tekoälylle.", revenueAtRisk: "Tuloriski", totalQueries: "Hakut yhteensä", priorityGaps: "Prioriteettiaukot", avgCpc: "Keskim. CPC", topBlindSpotOpportunities: "TÄRKEIMMÄT MAHDOLISUUDET", gapDistribution: "Aukkojen jakauma", neither: "Ei kumpikaan", others: "Muut", topValue: "Korkein arvo", closing: "sokeaa kohtaa, ", fixGapsCta: "Korjaa nämä aukot saadaksesi Google- ja tekoälyliikennettä.", demand: "kysyntä", val: "arvo" },
};

const MARKET_SHARE: Record<VideoLangCode, MarketShareStrings> = {
  en: { title: "Market Share of Attention", tagline: "How much AI attention does your brand command?", attentionScores: "Attention Scores", marketScore: "Market Score", aiMention: "AI Mention", organic: "Organic", defaultLeader: "DEFAULT LEADER", challenger: "CHALLENGER", aiMentionsQueries: "AI mentions / queries analyzed", engineBreakdown: "AI ENGINE BREAKDOWN", aiShareVsOrganic: "AI Share vs Organic", closingDefaultLeader: "Your brand is the DEFAULT LEADER in AI recommendations.", closingChallenger: "Grow AI visibility to become the default choice." },
  es: { title: "Cuota de Mercado de Atención", tagline: "¿Cuánta atención de IA capta tu marca?", attentionScores: "Puntuación de Atención", marketScore: "Puntuación de Mercado", aiMention: "Mención IA", organic: "Orgánico", defaultLeader: "LÍDER POR DEFECTO", challenger: "COMPETIDOR", aiMentionsQueries: "menciones IA / consultas analizadas", engineBreakdown: "DESGLOSE POR MOTOR IA", aiShareVsOrganic: "Cuota IA vs Orgánico", closingDefaultLeader: "Tu marca es el LÍDER POR DEFECTO en recomendaciones IA.", closingChallenger: "Aumenta la visibilidad en IA para ser la opción predeterminada." },
  fr: { title: "Part de Marché de l'Attention", tagline: "Quelle attention IA votre marque attire-t-elle ?", attentionScores: "Scores d'Attention", marketScore: "Score Marché", aiMention: "Mention IA", organic: "Organique", defaultLeader: "LEADER PAR DÉFAUT", challenger: "CHALLENGER", aiMentionsQueries: "mentions IA / requêtes analysées", engineBreakdown: "RÉPARTITION PAR MOTEUR IA", aiShareVsOrganic: "Part IA vs Organique", closingDefaultLeader: "Votre marque est le LEADER PAR DÉFAUT dans les recommandations IA.", closingChallenger: "Développez la visibilité IA pour devenir le choix par défaut." },
  de: { title: "Marktanteil der Aufmerksamkeit", tagline: "Wie viel KI-Aufmerksamkeit erhält Ihre Marke?", attentionScores: "Aufmerksamkeits-Scores", marketScore: "Markt-Score", aiMention: "KI-Erwähnung", organic: "Organisch", defaultLeader: "STANDARD-FÜHRER", challenger: "HERAUSFORDERER", aiMentionsQueries: "KI-Erwähnungen / analysierte Anfragen", engineBreakdown: "KI-MOTOREN-AUFschlüsselung", aiShareVsOrganic: "KI-Anteil vs Organisch", closingDefaultLeader: "Ihre Marke ist der STANDARD-FÜHRER bei KI-Empfehlungen.", closingChallenger: "Steigern Sie die KI-Sichtbarkeit, um die Standardwahl zu werden." },
  zh: { title: "注意力市场份额", tagline: "您的品牌在AI注意力中占多少？", attentionScores: "注意力得分", marketScore: "市场得分", aiMention: "AI提及", organic: "自然", defaultLeader: "默认领导者", challenger: "挑战者", aiMentionsQueries: "AI提及/分析查询", engineBreakdown: "AI引擎细分", aiShareVsOrganic: "AI份额 vs 自然", closingDefaultLeader: "您的品牌是AI推荐中的默认领导者。", closingChallenger: "提高AI可见度以成为默认选择。" },
  ja: { title: "注目シェア", tagline: "ブランドはAIの注目をどれだけ獲得していますか？", attentionScores: "注目スコア", marketScore: "市場スコア", aiMention: "AI言及", organic: "オーガニック", defaultLeader: "デフォルトリーダー", challenger: "チャレンジャー", aiMentionsQueries: "AI言及/分析クエリ", engineBreakdown: "AIエンジン内訳", aiShareVsOrganic: "AIシェア vs オーガニック", closingDefaultLeader: "ブランドはAI推奨のデフォルトリーダーです。", closingChallenger: "AI可視性を高めてデフォルト選択に。" },
  pt: { title: "Participação de Mercado da Atenção", tagline: "Quanta atenção de IA sua marca comanda?", attentionScores: "Scores de Atenção", marketScore: "Score de Mercado", aiMention: "Menção IA", organic: "Orgânico", defaultLeader: "LÍDER PADRÃO", challenger: "DESAFIANTE", aiMentionsQueries: "menções IA / consultas analisadas", engineBreakdown: "DETALHAMENTO POR MOTOR IA", aiShareVsOrganic: "Participação IA vs Orgânico", closingDefaultLeader: "Sua marca é o LÍDER PADRÃO em recomendações IA.", closingChallenger: "Aumente a visibilidade IA para se tornar a escolha padrão." },
  ar: { title: "حصة السوق من الانتباه", tagline: "كم انتباه الذكاء الاصطناعي تحصل عليه علامتك؟", attentionScores: "درجات الانتباه", marketScore: "درجة السوق", aiMention: "ذكر الذكاء الاصطناعي", organic: "عضوي", defaultLeader: "القائد الافتراضي", challenger: "منافس", aiMentionsQueries: "إشارات الذكاء الاصطناعي / الاستعلامات المحللة", engineBreakdown: "تفصيل محركات الذكاء الاصطناعي", aiShareVsOrganic: "حصة الذكاء الاصطناعي مقابل العضوي", closingDefaultLeader: "علامتك هي القائد الافتراضي في توصيات الذكاء الاصطناعي.", closingChallenger: "زد من ظهور الذكاء الاصطناعي لتصبح الخيار الافتراضي." },
  he: { title: "חלק שוק תשומת הלב", tagline: "כמה תשומת לב AI מקבלת המותג שלך?", attentionScores: "ציוני תשומת לב", marketScore: "ציון שוק", aiMention: "אזכור AI", organic: "אורגני", defaultLeader: "מוביל ברירת מחדל", challenger: "מתחרה", aiMentionsQueries: "אזכורי AI / שאילתות שנותחו", engineBreakdown: "פירוט מנועי AI", aiShareVsOrganic: "חלק AI מול אורגני", closingDefaultLeader: "המותג שלך הוא מוביל ברירת המחדל בהמלצות AI.", closingChallenger: "הגדל נראות AI כדי להפוך לבחירה ברירת המחדל." },
  ru: { title: "Доля рынка внимания", tagline: "Сколько внимания ИИ привлекает ваш бренд?", attentionScores: "Оценки внимания", marketScore: "Рыночная оценка", aiMention: "Упоминание ИИ", organic: "Органический", defaultLeader: "ЛИДЕР ПО УМОЛЧАНИЮ", challenger: "ПРЕТЕНДЕНТ", aiMentionsQueries: "упоминаний ИИ / проанализировано запросов", engineBreakdown: "РАЗБИВКА ПО ДВИЖКАМ ИИ", aiShareVsOrganic: "Доля ИИ vs Органический", closingDefaultLeader: "Ваш бренд — ЛИДЕР ПО УМОЛЧАНИЮ в рекомендациях ИИ.", closingChallenger: "Повысьте видимость ИИ, чтобы стать выбором по умолчанию." },
  it: { title: "Quota di Mercato dell'Attenzione", tagline: "Quanta attenzione IA attira il tuo brand?", attentionScores: "Punteggi di Attenzione", marketScore: "Punteggio Mercato", aiMention: "Menzione IA", organic: "Organico", defaultLeader: "LEADER DI DEFAULT", challenger: "SFIDANTE", aiMentionsQueries: "menzioni IA / query analizzate", engineBreakdown: "RIEPILOGO MOTORI IA", aiShareVsOrganic: "Quota IA vs Organico", closingDefaultLeader: "Il tuo brand è il LEADER DI DEFAULT nelle raccomandazioni IA.", closingChallenger: "Aumenta la visibilità IA per diventare la scelta predefinita." },
  nl: { title: "Marktaandeel van aandacht", tagline: "Hoeveel AI-aandacht trekt jouw merk?", attentionScores: "Aandachtsscores", marketScore: "Marktscore", aiMention: "AI-vermelding", organic: "Organisch", defaultLeader: "STANDAARDLEIDER", challenger: "UITDAGER", aiMentionsQueries: "AI-vermeldingen / geanalyseerde zoekopdrachten", engineBreakdown: "AI-MOTORENOVERZICHT", aiShareVsOrganic: "AI-aandeel vs Organisch", closingDefaultLeader: "Jouw merk is de STANDAARDLEIDER in AI-aanbevelingen.", closingChallenger: "Vergroot AI-zichtbaarheid om de standaardkeuze te worden." },
  pl: { title: "Udział w Rynku Uwagi", tagline: "Ile uwagi AI przyciąga Twoja marka?", attentionScores: "Wyniki Uwagi", marketScore: "Wynik Rynku", aiMention: "Wzmianka AI", organic: "Organiczny", defaultLeader: "LIDER DOMYŚLNY", challenger: "RYWAL", aiMentionsQueries: "wzmianek AI / przeanalizowanych zapytań", engineBreakdown: "PODZIAŁ SILNIKÓW AI", aiShareVsOrganic: "Udział AI vs Organiczny", closingDefaultLeader: "Twoja marka jest LIDEREM DOMYŚLNYM w rekomendacjach AI.", closingChallenger: "Zwiększ widoczność AI, aby stać się domyślnym wyborem." },
  ko: { title: "주의 시장 점유율", tagline: "브랜드가 AI의 주의를 얼마나 끌고 있나요?", attentionScores: "주의 점수", marketScore: "시장 점수", aiMention: "AI 언급", organic: "자연", defaultLeader: "기본 리더", challenger: "도전자", aiMentionsQueries: "AI 언급 / 분석된 쿼리", engineBreakdown: "AI 엔진 분석", aiShareVsOrganic: "AI 점유율 vs 자연", closingDefaultLeader: "브랜드는 AI 추천의 기본 리더입니다.", closingChallenger: "AI 가시성을 높여 기본 선택이 되세요." },
  tr: { title: "Dikkat Pazar Payı", tagline: "Markanız ne kadar yapay zeka dikkati çekiyor?", attentionScores: "Dikkat Skorları", marketScore: "Pazar Skoru", aiMention: "Yapay Zeka Bahsi", organic: "Organik", defaultLeader: "VARSayILAN LİDER", challenger: "RAKİP", aiMentionsQueries: "yapay zeka bahsi / analiz edilen sorgu", engineBreakdown: "YAPAY ZEKA MOTOR DAĞILIMI", aiShareVsOrganic: "Yapay Zeka Payı vs Organik", closingDefaultLeader: "Markanız yapay zeka önerilerinde VARSayILAN LİDER.", closingChallenger: "Varsayılan seçim olmak için yapay zeka görünürlüğünü artırın." },
  hi: { title: "ध्यान का बाजार हिस्सा", tagline: "आपका ब्रांड कितना AI ध्यान आकर्षित करता है?", attentionScores: "ध्यान स्कोर", marketScore: "बाजार स्कोर", aiMention: "AI उल्लेख", organic: "ऑर्गेनिक", defaultLeader: "डिफ़ॉल्ट लीडर", challenger: "चुनौती देने वाला", aiMentionsQueries: "AI उल्लेख / विश्लेषित क्वेरी", engineBreakdown: "AI इंजन विभाजन", aiShareVsOrganic: "AI शेयर बनाम ऑर्गेनिक", closingDefaultLeader: "आपका ब्रांड AI सिफारिशों में डिफ़ॉल्ट लीडर है।", closingChallenger: "डिफ़ॉल्ट विकल्प बनने के लिए AI दृश्यता बढ़ाएं।" },
  th: { title: "ส่วนแบ่งตลาดความสนใจ", tagline: "แบรนด์ของคุณดึงความสนใจจาก AI ได้มากแค่ไหน?", attentionScores: "คะแนนความสนใจ", marketScore: "คะแนนตลาด", aiMention: "การกล่าวถึง AI", organic: "ออร์แกนิก", defaultLeader: "ผู้นำเริ่มต้น", challenger: "ผู้ท้าชิง", aiMentionsQueries: "การกล่าวถึง AI / คำค้นที่วิเคราะห์", engineBreakdown: "การแบ่งตามเครื่องมือ AI", aiShareVsOrganic: "ส่วนแบ่ง AI เทียบกับออร์แกนิก", closingDefaultLeader: "แบรนด์ของคุณเป็นผู้นำเริ่มต้นในการแนะนำของ AI", closingChallenger: "เพิ่มการมองเห็น AI เพื่อเป็นตัวเลือกเริ่มต้น" },
  vi: { title: "Thị Phần Chú Ý", tagline: "Thương hiệu của bạn thu hút bao nhiêu sự chú ý từ AI?", attentionScores: "Điểm Chú Ý", marketScore: "Điểm Thị Trường", aiMention: "Đề cập AI", organic: "Hữu cơ", defaultLeader: "DẪN ĐẦU MẶC ĐỊNH", challenger: "ĐỐI THỦ", aiMentionsQueries: "đề cập AI / truy vấn đã phân tích", engineBreakdown: "PHÂN TÍCH ĐỘNG CƠ AI", aiShareVsOrganic: "Thị phần AI vs Hữu cơ", closingDefaultLeader: "Thương hiệu của bạn là DẪN ĐẦU MẶC ĐỊNH trong đề xuất AI.", closingChallenger: "Tăng khả năng hiển thị AI để trở thành lựa chọn mặc định." },
  id: { title: "Bagian Pasar Perhatian", tagline: "Berapa banyak perhatian AI yang didapat merek Anda?", attentionScores: "Skor Perhatian", marketScore: "Skor Pasar", aiMention: "Sebutan AI", organic: "Organik", defaultLeader: "PEMIMPIN DEFAULT", challenger: "PENANTANG", aiMentionsQueries: "sebutan AI / kueri dianalisis", engineBreakdown: "RINCIAN MESIN AI", aiShareVsOrganic: "Bagian AI vs Organik", closingDefaultLeader: "Merek Anda adalah PEMIMPIN DEFAULT dalam rekomendasi AI.", closingChallenger: "Tingkatkan visibilitas AI untuk menjadi pilihan default." },
  sv: { title: "Uppmärksamhetsandel", tagline: "Hur mycket AI-uppmärksamhet får ditt varumärke?", attentionScores: "Uppmärksamhetspoäng", marketScore: "Marknadspoäng", aiMention: "AI-nämnande", organic: "Organisk", defaultLeader: "STANDARD LEDARE", challenger: "UTMANARE", aiMentionsQueries: "AI-nämnanden / analyserade sökningar", engineBreakdown: "AI-MOTORFÖRDELNING", aiShareVsOrganic: "AI-andel vs Organisk", closingDefaultLeader: "Ditt varumärke är STANDARD LEDARE i AI-rekommendationer.", closingChallenger: "Öka AI-synlighet för att bli standardvalet." },
  no: { title: "Oppmerksomhetsandel", tagline: "Hvor mye AI-oppmerksomhet får merkevaren din?", attentionScores: "Oppmerksomhetspoeng", marketScore: "Markedspoeng", aiMention: "AI-omtale", organic: "Organisk", defaultLeader: "STANDARD LEDER", challenger: "UTFORDER", aiMentionsQueries: "AI-omtaler / analyserte søk", engineBreakdown: "AI-MOTORFORDELING", aiShareVsOrganic: "AI-andel vs Organisk", closingDefaultLeader: "Merkevaren din er STANDARD LEDER i AI-anbefalinger.", closingChallenger: "Øk AI-synlighet for å bli standardvalget." },
  da: { title: "Opmarksomhedsandel", tagline: "Hvor meget AI-opmærksomhed får dit brand?", attentionScores: "Opmarksomhedsscorer", marketScore: "Markedsscore", aiMention: "AI-omtale", organic: "Organisk", defaultLeader: "STANDARD LEDER", challenger: "UDfordER", aiMentionsQueries: "AI-omtaler / analyserede forespørgsler", engineBreakdown: "AI-MOTOROPDeling", aiShareVsOrganic: "AI-andel vs Organisk", closingDefaultLeader: "Dit brand er STANDARD LEDER i AI-anbefalinger.", closingChallenger: "Øg AI-synlighed for at blive standardvalget." },
  fi: { title: "Huomion markkinaosuus", tagline: "Kuinka paljon tekoälyhuomiota brändisi saa?", attentionScores: "Huomiopisteet", marketScore: "Markkinapisteet", aiMention: "Tekoälymaininta", organic: "Orgaaninen", defaultLeader: "Oletusjohtaja", challenger: "Haastaja", aiMentionsQueries: "tekoälymainintoja / analysoituja hakuja", engineBreakdown: "Tekoälymoottorijakauma", aiShareVsOrganic: "Tekoälyosuus vs Orgaaninen", closingDefaultLeader: "Brändisi on oletusjohtaja tekoälysuosituksissa.", closingChallenger: "Kasvata tekoälynäkyvyyttä tullaksesi oletusvalinnaksi." },
};

// Strategic Blind Spots - subset for brevity; fallback to instruction for others
const STRATEGIC_BLIND_SPOTS: Record<VideoLangCode, StrategicBlindSpotsStrings> = {
  en: { title: "Strategic Blind Spots", tagline: "Topics with demand. Zero presence.", whatAreWeIgnoring: "What Are We Ignoring?", ignored: "Ignored", score: "Score", aiBlind: "AI Blind", urgent: "Urgent", topBlindSpots: "TOP BLIND SPOTS", priority: "Priority", high: "High", med: "Med", low: "Low", aiGap: "AI Gap", ignores: "Ignores", mentions: "Mentions", closing: "gaps |", worstAiGap: "Worst AI gap:", fixFirst: "Fix first:" },
  es: { title: "Puntos Ciegos Estratégicos", tagline: "Temas con demanda. Cero presencia.", whatAreWeIgnoring: "¿Qué estamos ignorando?", ignored: "Ignorados", score: "Puntuación", aiBlind: "IA Ciego", urgent: "Urgente", topBlindSpots: "PRINCIPALES PUNTOS CIEGOS", priority: "Prioridad", high: "Alto", med: "Med", low: "Bajo", aiGap: "Brecha IA", ignores: "Ignora", mentions: "Menciona", closing: "brechas |", worstAiGap: "Peor brecha IA:", fixFirst: "Corregir primero:" },
  fr: { title: "Angles Morts Stratégiques", tagline: "Sujets à forte demande. Zéro présence.", whatAreWeIgnoring: "Que négligeons-nous ?", ignored: "Négligés", score: "Score", aiBlind: "IA Aveugle", urgent: "Urgent", topBlindSpots: "PRINCIPAUX ANGLES MORTS", priority: "Priorité", high: "Élevé", med: "Moyen", low: "Faible", aiGap: "Écart IA", ignores: "Ignore", mentions: "Mentionne", closing: "angles morts |", worstAiGap: "Pire écart IA:", fixFirst: "Corriger d'abord:" },
  de: { title: "Strategische tote Winkel", tagline: "Themen mit Nachfrage. Null Präsenz.", whatAreWeIgnoring: "Was ignorieren wir?", ignored: "Ignoriert", score: "Punktzahl", aiBlind: "KI-Blind", urgent: "Dringend", topBlindSpots: "TOP TOTE WINKEL", priority: "Priorität", high: "Hoch", med: "Mittel", low: "Niedrig", aiGap: "KI-Lücke", ignores: "Ignoriert", mentions: "Erwähnt", closing: "tote Winkel |", worstAiGap: "Schlimmste KI-Lücke:", fixFirst: "Zuerst beheben:" },
  zh: { title: "战略盲点", tagline: "有需求的主题。零存在。", whatAreWeIgnoring: "我们忽略了什么？", ignored: "已忽略", score: "得分", aiBlind: "AI盲点", urgent: "紧急", topBlindSpots: "主要盲点", priority: "优先级", high: "高", med: "中", low: "低", aiGap: "AI缺口", ignores: "忽略", mentions: "提及", closing: "个盲点 |", worstAiGap: "最差AI缺口：", fixFirst: "优先修复：" },
  ja: { title: "戦略的盲点", tagline: "需要のあるトピック。存在ゼロ。", whatAreWeIgnoring: "何を無視していますか？", ignored: "無視", score: "スコア", aiBlind: "AI盲点", urgent: "緊急", topBlindSpots: "主要な盲点", priority: "優先度", high: "高", med: "中", low: "低", aiGap: "AIギャップ", ignores: "無視", mentions: "言及", closing: "個の盲点 |", worstAiGap: "最悪のAIギャップ：", fixFirst: "最優先で修正：" },
  pt: { title: "Pontos Cegos Estratégicos", tagline: "Tópicos com demanda. Zero presença.", whatAreWeIgnoring: "O que estamos ignorando?", ignored: "Ignorados", score: "Pontuação", aiBlind: "IA Cego", urgent: "Urgente", topBlindSpots: "PRINCIPAIS PONTOS CEGOS", priority: "Prioridade", high: "Alto", med: "Méd", low: "Baixo", aiGap: "Lacuna IA", ignores: "Ignora", mentions: "Menciona", closing: "pontos cegos |", worstAiGap: "Pior lacuna IA:", fixFirst: "Corrigir primeiro:" },
  ar: { title: "النقاط العمياء الاستراتيجية", tagline: "مواضيع ذات طلب. صفر حضور.", whatAreWeIgnoring: "ماذا نتجاهل؟", ignored: "متجاهل", score: "الدرجة", aiBlind: "الذكاء الاصطناعي أعمى", urgent: "عاجل", topBlindSpots: "أهم النقاط العمياء", priority: "الأولوية", high: "عالي", med: "متوسط", low: "منخفض", aiGap: "فجوة الذكاء الاصطناعي", ignores: "يتجاهل", mentions: "يذكر", closing: "نقاط عمياء |", worstAiGap: "أسوأ فجوة ذكاء اصطناعي:", fixFirst: "إصلاح أولاً:" },
  he: { title: "נקודות עיוורון אסטרטגיות", tagline: "נושאים עם ביקוש. אפס נוכחות.", whatAreWeIgnoring: "מה אנחנו מתעלמים?", ignored: "מתעלמים", score: "ציון", aiBlind: "AI עיוור", urgent: "דחוף", topBlindSpots: "נקודות עיוורון עיקריות", priority: "עדיפות", high: "גבוה", med: "בינוני", low: "נמוך", aiGap: "פער AI", ignores: "מתעלם", mentions: "מזכיר", closing: "פערים |", worstAiGap: "פער AI הגרוע:", fixFirst: "תקן קודם:" },
  ru: { title: "Стратегические слепые зоны", tagline: "Темы с спросом. Нулевое присутствие.", whatAreWeIgnoring: "Что мы игнорируем?", ignored: "Игнорировано", score: "Оценка", aiBlind: "ИИ слепой", urgent: "Срочно", topBlindSpots: "ОСНОВНЫЕ СЛЕПЫЕ ЗОНЫ", priority: "Приоритет", high: "Высокий", med: "Средний", low: "Низкий", aiGap: "Разрыв ИИ", ignores: "Игнорирует", mentions: "Упоминает", closing: "слепых зон |", worstAiGap: "Худший разрыв ИИ:", fixFirst: "Исправить в первую очередь:" },
  it: { title: "Punti Ciechi Strategici", tagline: "Argomenti con domanda. Zero presenza.", whatAreWeIgnoring: "Cosa stiamo ignorando?", ignored: "Ignorati", score: "Punteggio", aiBlind: "IA Cieco", urgent: "Urgente", topBlindSpots: "PRINCIPALI PUNTI CIECHI", priority: "Priorità", high: "Alto", med: "Med", low: "Basso", aiGap: "Lacuna IA", ignores: "Ignora", mentions: "Menziona", closing: "punti ciechi |", worstAiGap: "Peggiore lacuna IA:", fixFirst: "Correggere prima:" },
  nl: { title: "Strategische blinde vlekken", tagline: "Onderwerpen met vraag. Geen aanwezigheid.", whatAreWeIgnoring: "Wat negeren we?", ignored: "Genegeerd", score: "Score", aiBlind: "AI-blind", urgent: "Urgent", topBlindSpots: "TOP BLINDE VLEKKEN", priority: "Prioriteit", high: "Hoog", med: "Gem", low: "Laag", aiGap: "AI-hiaat", ignores: "Negeert", mentions: "Vermeldt", closing: "blinde vlekken |", worstAiGap: "Slechtste AI-hiaat:", fixFirst: "Eerst oplossen:" },
  pl: { title: "Strategiczne martwe punkty", tagline: "Tematy z popytem. Zero obecności.", whatAreWeIgnoring: "Co ignorujemy?", ignored: "Zignorowane", score: "Wynik", aiBlind: "AI ślepy", urgent: "Pilne", topBlindSpots: "GŁÓWNE MARTWE PUNKTY", priority: "Priorytet", high: "Wysoki", med: "Śr", low: "Niski", aiGap: "Luka AI", ignores: "Ignoruje", mentions: "Wspomina", closing: "martwych punktów |", worstAiGap: "Najgorsza luka AI:", fixFirst: "Napraw najpierw:" },
  ko: { title: "전략적 맹점", tagline: "수요가 있는 주제. 존재 없음.", whatAreWeIgnoring: "무엇을 무시하고 있나요?", ignored: "무시됨", score: "점수", aiBlind: "AI 맹점", urgent: "긴급", topBlindSpots: "주요 맹점", priority: "우선순위", high: "높음", med: "중", low: "낮음", aiGap: "AI 갭", ignores: "무시", mentions: "언급", closing: "개 맹점 |", worstAiGap: "최악의 AI 갭:", fixFirst: "우선 수정:" },
  tr: { title: "Stratejik Kör Noktalar", tagline: "Talep olan konular. Sıfır varlık.", whatAreWeIgnoring: "Neyi görmezden geliyoruz?", ignored: "Yok sayıldı", score: "Puan", aiBlind: "Yapay Zeka Kör", urgent: "Acil", topBlindSpots: "ANA KÖR NOKTALAR", priority: "Öncelik", high: "Yüksek", med: "Orta", low: "Düşük", aiGap: "Yapay Zeka Boşluğu", ignores: "Yok sayar", mentions: "Bahseder", closing: "kör nokta |", worstAiGap: "En kötü yapay zeka boşluğu:", fixFirst: "Önce düzelt:" },
  hi: { title: "रणनीतिक अंध स्थान", tagline: "मांग वाले विषय। शून्य उपस्थिति।", whatAreWeIgnoring: "हम क्या अनदेखा कर रहे हैं?", ignored: "अनदेखा", score: "स्कोर", aiBlind: "AI अंध", urgent: "जरूरी", topBlindSpots: "मुख्य अंध स्थान", priority: "प्राथमिकता", high: "उच्च", med: "मध्य", low: "निम्न", aiGap: "AI अंतराल", ignores: "अनदेखा", mentions: "उल्लेख", closing: "अंतराल |", worstAiGap: "सबसे खराब AI अंतराल:", fixFirst: "पहले ठीक करें:" },
  th: { title: "จุดบอดเชิงกลยุทธ์", tagline: "หัวข้อที่มีความต้องการ ไม่มีการปรากฏตัว", whatAreWeIgnoring: "เรากำลังเพิกเฉยอะไร?", ignored: "เพิกเฉย", score: "คะแนน", aiBlind: "AI บอด", urgent: "เร่งด่วน", topBlindSpots: "จุดบอดหลัก", priority: "ลำดับความสำคัญ", high: "สูง", med: "กลาง", low: "ต่ำ", aiGap: "ช่องว่าง AI", ignores: "เพิกเฉย", mentions: "กล่าวถึง", closing: "ช่องว่าง |", worstAiGap: "ช่องว่าง AI ที่แย่ที่สุด:", fixFirst: "แก้ไขก่อน:" },
  vi: { title: "Điểm mù Chiến lược", tagline: "Chủ đề có nhu cầu. Không có sự hiện diện.", whatAreWeIgnoring: "Chúng ta đang bỏ qua gì?", ignored: "Bỏ qua", score: "Điểm", aiBlind: "AI mù", urgent: "Khẩn cấp", topBlindSpots: "ĐIỂM MÙ CHÍNH", priority: "Ưu tiên", high: "Cao", med: "TB", low: "Thấp", aiGap: "Khoảng trống AI", ignores: "Bỏ qua", mentions: "Đề cập", closing: "điểm mù |", worstAiGap: "Khoảng trống AI tệ nhất:", fixFirst: "Sửa trước:" },
  id: { title: "Titik Buta Strategis", tagline: "Topik dengan permintaan. Nol kehadiran.", whatAreWeIgnoring: "Apa yang kita abaikan?", ignored: "Diabaikan", score: "Skor", aiBlind: "AI Buta", urgent: "Mendesak", topBlindSpots: "TITIK BUTA UTAMA", priority: "Prioritas", high: "Tinggi", med: "Sedang", low: "Rendah", aiGap: "Kesenjangan AI", ignores: "Mengabaikan", mentions: "Menyebut", closing: "titik buta |", worstAiGap: "Kesenjangan AI terburuk:", fixFirst: "Perbaiki dulu:" },
  sv: { title: "Strategiska blinda fläckar", tagline: "Ämnen med efterfrågan. Noll närvaro.", whatAreWeIgnoring: "Vad ignorerar vi?", ignored: "Ignorerad", score: "Poäng", aiBlind: "AI-blind", urgent: "Brådskande", topBlindSpots: "FRÄMSTA BLINDA FLÄCKAR", priority: "Prioritet", high: "Hög", med: "Med", low: "Låg", aiGap: "AI-gap", ignores: "Ignorerar", mentions: "Nämner", closing: "blinda fläckar |", worstAiGap: "Sämsta AI-gap:", fixFirst: "Åtgärda först:" },
  no: { title: "Strategiske blindsoner", tagline: "Emner med etterspørsel. Null tilstedeværelse.", whatAreWeIgnoring: "Hva ignorerer vi?", ignored: "Ignorert", score: "Poeng", aiBlind: "AI-blind", urgent: "Haster", topBlindSpots: "VIKTIGSTE BLINDSONER", priority: "Prioritet", high: "Høy", med: "Middels", low: "Lav", aiGap: "AI-gap", ignores: "Ignorerer", mentions: "Nevner", closing: "blindsoner |", worstAiGap: "Verste AI-gap:", fixFirst: "Fiks først:" },
  da: { title: "Strategiske blinde vinkler", tagline: "Emner med efterspørgsel. Nul tilstedeværelse.", whatAreWeIgnoring: "Hvad ignorerer vi?", ignored: "Ignoreret", score: "Score", aiBlind: "AI-blind", urgent: "Haster", topBlindSpots: "VIGTIGSTE BLINDE VINKLER", priority: "Prioritet", high: "Høj", med: "Mellem", low: "Lav", aiGap: "AI-gab", ignores: "Ignorerer", mentions: "Nævner", closing: "blinde vinkler |", worstAiGap: "Værste AI-gab:", fixFirst: "Ret først:" },
  fi: { title: "Strategiset sokeat kohdat", tagline: "Aiheet kysynnällä. Nolla läsnäoloa.", whatAreWeIgnoring: "Mitä jätämme huomiotta?", ignored: "Ohitettu", score: "Pisteet", aiBlind: "Tekoäly sokea", urgent: "Kiireellinen", topBlindSpots: "TÄRKEIMMÄT SOKEAT KOHDAT", priority: "Prioriteetti", high: "Korkea", med: "Kesk", low: "Matala", aiGap: "Tekoälyaukko", ignores: "Ohittaa", mentions: "Mainitsee", closing: "sokeaa kohtaa |", worstAiGap: "Huonoin tekoälyaukko:", fixFirst: "Korjaa ensin:" },
};

// ── AI Search Presence translations ───────────────────────────────────────────
const AI_SEARCH_PRESENCE: Record<VideoLangCode, AiSearchPresenceStrings> = {
  en: { title: "AI Search Presence", tagline: "How visible are you across AI search engines?", presenceMetrics: "Presence Metrics", presenceScore: "Presence Score", mentions: "Mentions", engines: "Engines", sentiment: "Sentiment", positive: "Positive", negative: "Negative", neutral: "Neutral", engineBreakdown: "ENGINE BREAKDOWN", overallScore: "Overall Score", best: "Best", worst: "Worst", closingStrong: "Strong AI presence detected.", closingImprove: "Improve AI presence to reach more searchers." },
  es: { title: "Presencia en Búsqueda IA", tagline: "¿Qué tan visible eres en los motores de búsqueda IA?", presenceMetrics: "Métricas de Presencia", presenceScore: "Puntuación de Presencia", mentions: "Menciones", engines: "Motores", sentiment: "Sentimiento", positive: "Positivo", negative: "Negativo", neutral: "Neutral", engineBreakdown: "DESGLOSE POR MOTOR", overallScore: "Puntuación General", best: "Mejor", worst: "Peor", closingStrong: "Fuerte presencia de IA detectada.", closingImprove: "Mejora la presencia en IA para llegar a más buscadores." },
  fr: { title: "Présence IA en Recherche", tagline: "Quelle est votre visibilité sur les moteurs de recherche IA ?", presenceMetrics: "Métriques de Présence", presenceScore: "Score de Présence", mentions: "Mentions", engines: "Moteurs", sentiment: "Sentiment", positive: "Positif", negative: "Négatif", neutral: "Neutre", engineBreakdown: "RÉPARTITION PAR MOTEUR", overallScore: "Score Global", best: "Meilleur", worst: "Pire", closingStrong: "Forte présence IA détectée.", closingImprove: "Améliorez la présence IA pour toucher plus de chercheurs." },
  de: { title: "KI-Suchpräsenz", tagline: "Wie sichtbar sind Sie in KI-Suchmaschinen?", presenceMetrics: "Präsenz-Metriken", presenceScore: "Präsenz-Score", mentions: "Erwähnungen", engines: "Suchmaschinen", sentiment: "Stimmung", positive: "Positiv", negative: "Negativ", neutral: "Neutral", engineBreakdown: "MOTOREN-AUFschlüsselung", overallScore: "Gesamtscore", best: "Bester", worst: "Schlechtester", closingStrong: "Starke KI-Präsenz erkannt.", closingImprove: "Verbessern Sie die KI-Präsenz für mehr Sucher." },
  zh: { title: "AI搜索存在感", tagline: "您在AI搜索引擎中的可见度如何？", presenceMetrics: "存在感指标", presenceScore: "存在感得分", mentions: "提及", engines: "引擎", sentiment: "情感", positive: "积极", negative: "消极", neutral: "中性", engineBreakdown: "引擎细分", overallScore: "总体得分", best: "最佳", worst: "最差", closingStrong: "检测到强大的AI存在感。", closingImprove: "提高AI存在感以触达更多搜索者。" },
  ja: { title: "AI検索プレゼンス", tagline: "AI検索エンジンでの可視性は？", presenceMetrics: "プレゼンス指標", presenceScore: "プレゼンススコア", mentions: "言及", engines: "エンジン", sentiment: "センチメント", positive: "ポジティブ", negative: "ネガティブ", neutral: "ニュートラル", engineBreakdown: "エンジン内訳", overallScore: "総合スコア", best: "最高", worst: "最低", closingStrong: "強いAIプレゼンスを検出。", closingImprove: "AIプレゼンスを向上させてより多くの検索者に届けましょう。" },
  pt: { title: "Presença em Busca IA", tagline: "Quão visível você está nos motores de busca IA?", presenceMetrics: "Métricas de Presença", presenceScore: "Pontuação de Presença", mentions: "Menções", engines: "Motores", sentiment: "Sentimento", positive: "Positivo", negative: "Negativo", neutral: "Neutro", engineBreakdown: "DETALHAMENTO POR MOTOR", overallScore: "Pontuação Geral", best: "Melhor", worst: "Pior", closingStrong: "Forte presença IA detectada.", closingImprove: "Melhore a presença IA para alcançar mais pesquisadores." },
  ar: { title: "حضور البحث بالذكاء الاصطناعي", tagline: "ما مدى ظهورك في محركات البحث بالذكاء الاصطناعي؟", presenceMetrics: "مقاييس الحضور", presenceScore: "درجة الحضور", mentions: "الإشارات", engines: "المحركات", sentiment: "المشاعر", positive: "إيجابي", negative: "سلبي", neutral: "محايد", engineBreakdown: "تفصيل المحركات", overallScore: "الدرجة الإجمالية", best: "الأفضل", worst: "الأسوأ", closingStrong: "تم اكتشاف حضور قوي للذكاء الاصطناعي.", closingImprove: "حسّن حضور الذكاء الاصطناعي للوصول إلى المزيد من الباحثين." },
  he: { title: "נוכחות חיפוש AI", tagline: "כמה גלוי אתה במנועי חיפוש AI?", presenceMetrics: "מדדי נוכחות", presenceScore: "ציון נוכחות", mentions: "אזכורים", engines: "מנועים", sentiment: "סנטימנט", positive: "חיובי", negative: "שלילי", neutral: "ניטרלי", engineBreakdown: "פירוט מנועים", overallScore: "ציון כללי", best: "הכי טוב", worst: "הכי גרוע", closingStrong: "נוכחות AI חזקה זוהתה.", closingImprove: "שפר נוכחות AI להגעת יותר מחפשים." },
  ru: { title: "Присутствие в поиске ИИ", tagline: "Насколько вы заметны в поисковых системах ИИ?", presenceMetrics: "Метрики присутствия", presenceScore: "Оценка присутствия", mentions: "Упоминания", engines: "Движки", sentiment: "Тональность", positive: "Позитивная", negative: "Негативная", neutral: "Нейтральная", engineBreakdown: "Разбивка по движкам", overallScore: "Общая оценка", best: "Лучший", worst: "Худший", closingStrong: "Обнаружено сильное присутствие ИИ.", closingImprove: "Улучшите присутствие ИИ для охвата большего числа пользователей." },
  it: { title: "Presenza nella Ricerca IA", tagline: "Quanto sei visibile nei motori di ricerca IA?", presenceMetrics: "Metriche di Presenza", presenceScore: "Punteggio Presenza", mentions: "Menzioni", engines: "Motori", sentiment: "Sentimento", positive: "Positivo", negative: "Negativo", neutral: "Neutro", engineBreakdown: "RIEPILOGO MOTORI", overallScore: "Punteggio Complessivo", best: "Migliore", worst: "Peggiore", closingStrong: "Forte presenza IA rilevata.", closingImprove: "Migliora la presenza IA per raggiungere più ricercatori." },
  nl: { title: "AI-zoekzichtbaarheid", tagline: "Hoe zichtbaar bent u in AI-zoekmachines?", presenceMetrics: "Zichtbaarheidsmetrieken", presenceScore: "Zichtbaarheidsscore", mentions: "Vermeldingen", engines: "Zoekmachines", sentiment: "Sentiment", positive: "Positief", negative: "Negatief", neutral: "Neutraal", engineBreakdown: "MOTORENOVERZICHT", overallScore: "Algemene Score", best: "Beste", worst: "Slechtste", closingStrong: "Sterke AI-zichtbaarheid gedetecteerd.", closingImprove: "Verbeter AI-zichtbaarheid om meer zoekers te bereiken." },
  pl: { title: "Obecność w Wyszukiwarkach AI", tagline: "Jak widoczna jest Twoja marka w wyszukiwarkach AI?", presenceMetrics: "Metryki Obecności", presenceScore: "Wynik Obecności", mentions: "Wzmianki", engines: "Wyszukiwarki", sentiment: "Nastrój", positive: "Pozytywny", negative: "Negatywny", neutral: "Neutralny", engineBreakdown: "PODZIAŁ SILNIKÓW", overallScore: "Wynik Ogólny", best: "Najlepszy", worst: "Najgorszy", closingStrong: "Wykryto silną obecność AI.", closingImprove: "Zwiększ obecność AI, aby dotrzeć do większej liczby wyszukujących." },
  ko: { title: "AI 검색 존재감", tagline: "AI 검색 엔진에서 얼마나 보이나요?", presenceMetrics: "존재감 지표", presenceScore: "존재감 점수", mentions: "언급", engines: "엔진", sentiment: "감정", positive: "긍정", negative: "부정", neutral: "중립", engineBreakdown: "엔진 분석", overallScore: "종합 점수", best: "최고", worst: "최저", closingStrong: "강한 AI 존재감 감지됨.", closingImprove: "AI 존재감을 높여 더 많은 검색자에게 도달하세요." },
  tr: { title: "Yapay Zeka Arama Varlığı", tagline: "Yapay zeka arama motorlarında ne kadar görünürsünüz?", presenceMetrics: "Varlık Metrikleri", presenceScore: "Varlık Skoru", mentions: "Bahisler", engines: "Motorlar", sentiment: "Duygu", positive: "Pozitif", negative: "Negatif", neutral: "Nötr", engineBreakdown: "MOTOR DAĞILIMI", overallScore: "Genel Skor", best: "En İyi", worst: "En Kötü", closingStrong: "Güçlü yapay zeka varlığı tespit edildi.", closingImprove: "Daha fazla arayanlara ulaşmak için yapay zeka varlığını artırın." },
  hi: { title: "AI खोज उपस्थिति", tagline: "AI खोज इंजन में आप कितने दिखाई देते हैं?", presenceMetrics: "उपस्थिति मेट्रिक्स", presenceScore: "उपस्थिति स्कोर", mentions: "उल्लेख", engines: "इंजन", sentiment: "भावना", positive: "सकारात्मक", negative: "नकारात्मक", neutral: "तटस्थ", engineBreakdown: "इंजन विभाजन", overallScore: "समग्र स्कोर", best: "सर्वश्रेष्ठ", worst: "सबसे खराब", closingStrong: "मजबूत AI उपस्थिति का पता चला।", closingImprove: "अधिक खोजकर्ताओं तक पहुंचने के लिए AI उपस्थिति बढ़ाएं।" },
  th: { title: "การปรากฏตัวในการค้นหา AI", tagline: "คุณมองเห็นได้มากแค่ไหนในเครื่องมือค้นหา AI?", presenceMetrics: "เมตริกการปรากฏตัว", presenceScore: "คะแนนการปรากฏตัว", mentions: "การกล่าวถึง", engines: "เครื่องมือ", sentiment: "ความรู้สึก", positive: "เชิงบวก", negative: "เชิงลบ", neutral: "เป็นกลาง", engineBreakdown: "การแบ่งตามเครื่องมือ", overallScore: "คะแนนรวม", best: "ดีที่สุด", worst: "แย่ที่สุด", closingStrong: "ตรวจพบการปรากฏตัวของ AI ที่แข็งแกร่ง", closingImprove: "ปรับปรุงการปรากฏตัวของ AI เพื่อเข้าถึงผู้ค้นหามากขึ้น" },
  vi: { title: "Sự Hiện Diện Tìm Kiếm AI", tagline: "Bạn hiển thị như thế nào trên công cụ tìm kiếm AI?", presenceMetrics: "Chỉ số Hiện Diện", presenceScore: "Điểm Hiện Diện", mentions: "Đề cập", engines: "Công cụ", sentiment: "Cảm xúc", positive: "Tích cực", negative: "Tiêu cực", neutral: "Trung lập", engineBreakdown: "PHÂN TÍCH CÔNG CỤ", overallScore: "Điểm Tổng", best: "Tốt nhất", worst: "Tệ nhất", closingStrong: "Phát hiện sự hiện diện AI mạnh mẽ.", closingImprove: "Cải thiện sự hiện diện AI để tiếp cận nhiều người tìm kiếm hơn." },
  id: { title: "Kehadiran Pencarian AI", tagline: "Seberapa terlihat Anda di mesin pencari AI?", presenceMetrics: "Metrik Kehadiran", presenceScore: "Skor Kehadiran", mentions: "Sebutan", engines: "Mesin", sentiment: "Sentimen", positive: "Positif", negative: "Negatif", neutral: "Netral", engineBreakdown: "RINCIAN MESIN", overallScore: "Skor Keseluruhan", best: "Terbaik", worst: "Terburuk", closingStrong: "Kehadiran AI kuat terdeteksi.", closingImprove: "Tingkatkan kehadiran AI untuk menjangkau lebih banyak pencari." },
  sv: { title: "AI-sökningsnärvaro", tagline: "Hur synlig är du i AI-sökmotorer?", presenceMetrics: "Närvaromått", presenceScore: "Närvaropoäng", mentions: "Nämnanden", engines: "Sökmotorer", sentiment: "Sentiment", positive: "Positiv", negative: "Negativ", neutral: "Neutral", engineBreakdown: "MOTORFÖRDELNING", overallScore: "Totalpoäng", best: "Bäst", worst: "Sämst", closingStrong: "Stark AI-närvaro upptäckt.", closingImprove: "Förbättra AI-närvaro för att nå fler sökande." },
  no: { title: "AI-søkesynlighet", tagline: "Hvor synlig er du i AI-søkemotorer?", presenceMetrics: "Synlighetsmålinger", presenceScore: "Synlighetspoeng", mentions: "Omtaler", engines: "Søkemotorer", sentiment: "Følelse", positive: "Positiv", negative: "Negativ", neutral: "Nøytral", engineBreakdown: "MOTORFORDELING", overallScore: "Samlet poeng", best: "Beste", worst: "Verste", closingStrong: "Sterk AI-synlighet oppdaget.", closingImprove: "Forbedre AI-synlighet for å nå flere søkere." },
  da: { title: "AI-søgesynlighed", tagline: "Hvor synlig er du i AI-søgemotorer?", presenceMetrics: "Synlighedsmålinger", presenceScore: "Synlighedsscore", mentions: "Omtaler", engines: "Søgemotorer", sentiment: "Følelse", positive: "Positiv", negative: "Negativ", neutral: "Neutral", engineBreakdown: "MOTOROPDeling", overallScore: "Samlet score", best: "Bedste", worst: "Værste", closingStrong: "Stærk AI-synlighed opdaget.", closingImprove: "Forbedre AI-synlighed for at nå flere søgere." },
  fi: { title: "Tekoälyhaun läsnäolo", tagline: "Kuinka näkyvä olet tekoälyhakukoneissa?", presenceMetrics: "Läsnäolomittarit", presenceScore: "Läsnäolopisteet", mentions: "Maininnat", engines: "Hakut", sentiment: "Tunne", positive: "Positiivinen", negative: "Negatiivinen", neutral: "Neutraali", engineBreakdown: "Hakutjakauma", overallScore: "Kokonaispisteet", best: "Paras", worst: "Huonoin", closingStrong: "Vahva tekoälyn läsnäolo havaittu.", closingImprove: "Paranna tekoälyn läsnäoloa saavuttaaksesi enemmän hakijoita." },
};

// ── AI vs Google Gap translations ────────────────────────────────────────────
const AI_VS_GOOGLE_GAP: Record<VideoLangCode, AiVsGoogleGapStrings> = {
  en: { title: "AI vs Google Gap", tagline: "Where Google ranks you but AI ignores you.", visibilityGapReport: "Visibility Gap Report", aiRisk: "AI Risk", moderateGap: "Moderate Gap", balanced: "Balanced", seoOpp: "SEO Opp", avgGapScore: "Avg gap score", totalQueries: "Total queries", topAiRiskQueries: "TOP AI RISK QUERIES", bandSplit: "Band Split", seoOpportunity: "SEO Opportunity", closing: "queries strong on Google but invisible in AI. Fix these first to capture AI-driven traffic." },
  es: { title: "Brecha IA vs Google", tagline: "Donde Google te posiciona pero la IA te ignora.", visibilityGapReport: "Informe de Brecha de Visibilidad", aiRisk: "Riesgo IA", moderateGap: "Brecha Moderada", balanced: "Equilibrado", seoOpp: "Oport. SEO", avgGapScore: "Puntuación media de brecha", totalQueries: "Consultas totales", topAiRiskQueries: "PRINCIPALES CONSULTAS DE RIESGO IA", bandSplit: "División por Bandas", seoOpportunity: "Oportunidad SEO", closing: "consultas fuertes en Google pero invisibles en IA. Corrígelas primero para capturar tráfico impulsado por IA." },
  fr: { title: "Écart IA vs Google", tagline: "Où Google vous classe mais l'IA vous ignore.", visibilityGapReport: "Rapport d'Écart de Visibilité", aiRisk: "Risque IA", moderateGap: "Écart Modéré", balanced: "Équilibré", seoOpp: "Opp. SEO", avgGapScore: "Score d'écart moyen", totalQueries: "Requêtes totales", topAiRiskQueries: "PRINCIPALES REQUÊTES À RISQUE IA", bandSplit: "Répartition par Bandes", seoOpportunity: "Opportunité SEO", closing: "requêtes fortes sur Google mais invisibles en IA. Corrigez-les d'abord pour capter le trafic IA." },
  de: { title: "KI vs Google Lücke", tagline: "Wo Google Sie rankt, aber KI Sie ignoriert.", visibilityGapReport: "Sichtbarkeitslücken-Bericht", aiRisk: "KI-Risiko", moderateGap: "Moderate Lücke", balanced: "Ausgewogen", seoOpp: "SEO-Chance", avgGapScore: "Ø Lückenscore", totalQueries: "Anfragen gesamt", topAiRiskQueries: "TOP KI-RISIKO-ANFRAGEN", bandSplit: "Bandaufteilung", seoOpportunity: "SEO-Chance", closing: "Anfragen stark bei Google, aber unsichtbar in KI. Beheben Sie diese zuerst für KI-Traffic." },
  zh: { title: "AI与谷歌差距", tagline: "谷歌排名靠前但AI忽略你。", visibilityGapReport: "可见性差距报告", aiRisk: "AI风险", moderateGap: "中度差距", balanced: "平衡", seoOpp: "SEO机会", avgGapScore: "平均差距得分", totalQueries: "总查询数", topAiRiskQueries: "主要AI风险查询", bandSplit: "波段分布", seoOpportunity: "SEO机会", closing: "个查询在谷歌表现强但在AI中不可见。优先修复以获取AI流量。" },
  ja: { title: "AI対Googleギャップ", tagline: "Googleでは上位だがAIでは無視される。", visibilityGapReport: "可視性ギャップレポート", aiRisk: "AIリスク", moderateGap: "中程度ギャップ", balanced: "バランス", seoOpp: "SEO機会", avgGapScore: "平均ギャップスコア", totalQueries: "総クエリ数", topAiRiskQueries: "主要AIリスククエリ", bandSplit: "バンド分割", seoOpportunity: "SEO機会", closing: "件のクエリはGoogleで強いがAIでは不可視。AIトラフィック獲得のため優先修正。" },
  pt: { title: "Lacuna IA vs Google", tagline: "Onde o Google te ranqueia mas a IA te ignora.", visibilityGapReport: "Relatório de Lacuna de Visibilidade", aiRisk: "Risco IA", moderateGap: "Lacuna Moderada", balanced: "Equilibrado", seoOpp: "Oport. SEO", avgGapScore: "Pontuação média de lacuna", totalQueries: "Consultas totais", topAiRiskQueries: "PRINCIPAIS CONSULTAS DE RISCO IA", bandSplit: "Divisão por Bandas", seoOpportunity: "Oportunidade SEO", closing: "consultas fortes no Google mas invisíveis na IA. Corrija primeiro para capturar tráfego IA." },
  ar: { title: "فجوة الذكاء الاصطناعي مقابل جوجل", tagline: "حيث يصنفك جوجل لكن الذكاء الاصطناعي يتجاهلك.", visibilityGapReport: "تقرير فجوة الرؤية", aiRisk: "خطر الذكاء الاصطناعي", moderateGap: "فجوة معتدلة", balanced: "متوازن", seoOpp: "فرصة تحسين محركات البحث", avgGapScore: "متوسط درجة الفجوة", totalQueries: "إجمالي الاستعلامات", topAiRiskQueries: "أهم استعلامات خطر الذكاء الاصطناعي", bandSplit: "تقسيم النطاق", seoOpportunity: "فرصة تحسين محركات البحث", closing: "استعلامات قوية في جوجل لكن غير مرئية في الذكاء الاصطناعي. أصلحها أولاً لاستقطاب حركة الذكاء الاصطناعي." },
  he: { title: "פער AI מול Google", tagline: "איפה ש-Google מדרג אותך אבל AI מתעלם.", visibilityGapReport: "דוח פער נראות", aiRisk: "סיכון AI", moderateGap: "פער בינוני", balanced: "מאוזן", seoOpp: "הזדמנות SEO", avgGapScore: "ציון פער ממוצע", totalQueries: "סה״כ שאילתות", topAiRiskQueries: "שאילתות סיכון AI עיקריות", bandSplit: "פיצול פס", seoOpportunity: "הזדמנות SEO", closing: "שאילתות חזקות ב-Google אבל בלתי נראות ב-AI. תקן קודם לתפיסת תעבורת AI." },
  ru: { title: "Разрыв ИИ vs Google", tagline: "Где Google ранжирует вас, но ИИ игнорирует.", visibilityGapReport: "Отчёт о разрыве видимости", aiRisk: "Риск ИИ", moderateGap: "Умеренный разрыв", balanced: "Сбалансировано", seoOpp: "SEO-возможность", avgGapScore: "Средний разрыв", totalQueries: "Всего запросов", topAiRiskQueries: "ОСНОВНЫЕ РИСК-ЗАПРОСЫ ИИ", bandSplit: "Разбивка по полосам", seoOpportunity: "SEO-возможность", closing: "запросов сильны в Google, но невидимы в ИИ. Исправьте в первую очередь для ИИ-трафика." },
  it: { title: "Lacuna IA vs Google", tagline: "Dove Google ti classifica ma l'IA ti ignora.", visibilityGapReport: "Rapporto Lacuna Visibilità", aiRisk: "Rischio IA", moderateGap: "Lacuna Moderata", balanced: "Bilanciato", seoOpp: "Opp. SEO", avgGapScore: "Punteggio lacuna medio", totalQueries: "Query totali", topAiRiskQueries: "PRINCIPALI QUERY A RISCHIO IA", bandSplit: "Divisione per Bande", seoOpportunity: "Opportunità SEO", closing: "query forti su Google ma invisibili in IA. Correggere prima per traffico IA." },
  nl: { title: "AI vs Google Kloof", tagline: "Waar Google je rankt maar AI je negeert.", visibilityGapReport: "Zichtbaarheidskloofrapport", aiRisk: "AI-risico", moderateGap: "Matige kloof", balanced: "Gebalanceerd", seoOpp: "SEO-kans", avgGapScore: "Gem. kloofscore", totalQueries: "Totaal zoekopdrachten", topAiRiskQueries: "TOP AI-RISICOZOEKOPDRACHTEN", bandSplit: "Bandverdeling", seoOpportunity: "SEO-kans", closing: "zoekopdrachten sterk op Google maar onzichtbaar in AI. Los eerst op voor AI-verkeer." },
  pl: { title: "Luka AI vs Google", tagline: "Gdzie Google Cię rankuje, ale AI Cię ignoruje.", visibilityGapReport: "Raport Luki Widoczności", aiRisk: "Ryzyko AI", moderateGap: "Umiarkowana luka", balanced: "Zrównoważony", seoOpp: "Szansa SEO", avgGapScore: "Śr. wynik luki", totalQueries: "Łączne zapytania", topAiRiskQueries: "GŁÓWNE ZAPYTANIA RYZYKA AI", bandSplit: "Podział pasm", seoOpportunity: "Szansa SEO", closing: "zapytań silnych w Google, niewidocznych w AI. Napraw najpierw dla ruchu AI." },
  ko: { title: "AI 대 Google 갭", tagline: "Google에서는 순위가 있지만 AI에서는 무시됩니다.", visibilityGapReport: "가시성 갭 보고서", aiRisk: "AI 위험", moderateGap: "중간 갭", balanced: "균형", seoOpp: "SEO 기회", avgGapScore: "평균 갭 점수", totalQueries: "총 쿼리", topAiRiskQueries: "주요 AI 위험 쿼리", bandSplit: "밴드 분할", seoOpportunity: "SEO 기회", closing: "개 쿼리가 Google에서는 강하지만 AI에서는 보이지 않습니다. AI 트래픽 확보를 위해 우선 수정하세요." },
  tr: { title: "Yapay Zeka vs Google Boşluğu", tagline: "Google sıralıyor ama yapay zeka görmezden geliyor.", visibilityGapReport: "Görünürlük Boşluğu Raporu", aiRisk: "Yapay Zeka Riski", moderateGap: "Orta Boşluk", balanced: "Dengeli", seoOpp: "SEO Fırsatı", avgGapScore: "Ort. boşluk puanı", totalQueries: "Toplam sorgu", topAiRiskQueries: "ANA YAPAY ZEKA RİSK SORGULARI", bandSplit: "Bant Bölünmesi", seoOpportunity: "SEO Fırsatı", closing: "sorgu Google'da güçlü ama yapay zekada görünmez. Yapay zeka trafiği için önce düzeltin." },
  hi: { title: "AI बनाम Google अंतराल", tagline: "जहां Google रैंक करता है लेकिन AI अनदेखा करता है।", visibilityGapReport: "दृश्यता अंतराल रिपोर्ट", aiRisk: "AI जोखिम", moderateGap: "मध्यम अंतराल", balanced: "संतुलित", seoOpp: "SEO अवसर", avgGapScore: "औसत अंतराल स्कोर", totalQueries: "कुल क्वेरी", topAiRiskQueries: "मुख्य AI जोखिम क्वेरी", bandSplit: "बैंड विभाजन", seoOpportunity: "SEO अवसर", closing: "क्वेरी Google में मजबूत लेकिन AI में अदृश्य। AI ट्रैफिक के लिए पहले ठीक करें।" },
  th: { title: "ช่องว่าง AI เทียบกับ Google", tagline: "ที่ Google จัดอันดับคุณแต่ AI ไม่สนใจ", visibilityGapReport: "รายงานช่องว่างการมองเห็น", aiRisk: "ความเสี่ยง AI", moderateGap: "ช่องว่างปานกลาง", balanced: "สมดุล", seoOpp: "โอกาส SEO", avgGapScore: "คะแนนช่องว่างเฉลี่ย", totalQueries: "คำค้นรวม", topAiRiskQueries: "คำค้นความเสี่ยง AI หลัก", bandSplit: "การแบ่งแถบ", seoOpportunity: "โอกาส SEO", closing: "คำค้นที่แข็งแกร่งใน Google แต่มองไม่เห็นใน AI แก้ไขก่อนเพื่อดึงการเข้าชมจาก AI" },
  vi: { title: "Khoảng trống AI vs Google", tagline: "Nơi Google xếp hạng bạn nhưng AI bỏ qua.", visibilityGapReport: "Báo cáo Khoảng trống Hiển thị", aiRisk: "Rủi ro AI", moderateGap: "Khoảng trống Vừa phải", balanced: "Cân bằng", seoOpp: "Cơ hội SEO", avgGapScore: "Điểm khoảng trống TB", totalQueries: "Tổng truy vấn", topAiRiskQueries: "TRUY VẤN RỦI RO AI CHÍNH", bandSplit: "Chia nhóm", seoOpportunity: "Cơ hội SEO", closing: "truy vấn mạnh trên Google nhưng vô hình trong AI. Sửa trước để thu hút lưu lượng AI." },
  id: { title: "Kesenjangan AI vs Google", tagline: "Di mana Google meranking Anda tapi AI mengabaikan.", visibilityGapReport: "Laporan Kesenjangan Visibilitas", aiRisk: "Risiko AI", moderateGap: "Kesenjangan Sedang", balanced: "Seimbang", seoOpp: "Peluang SEO", avgGapScore: "Skor kesenjangan rata-rata", totalQueries: "Total kueri", topAiRiskQueries: "KUERI RISIKO AI UTAMA", bandSplit: "Pembagian Pita", seoOpportunity: "Peluang SEO", closing: "kueri kuat di Google tapi tak terlihat di AI. Perbaiki dulu untuk lalu lintas AI." },
  sv: { title: "AI vs Google-gap", tagline: "Där Google rankar dig men AI ignorerar dig.", visibilityGapReport: "Synlighetsgapsrapport", aiRisk: "AI-risker", moderateGap: "Måttligt gap", balanced: "Balanserad", seoOpp: "SEO-möjlighet", avgGapScore: "Snitt gap-poäng", totalQueries: "Totalt antal sökningar", topAiRiskQueries: "FRÄMSTA AI-RISKSÖKNINGAR", bandSplit: "Bandfördelning", seoOpportunity: "SEO-möjlighet", closing: "sökningar starka på Google men osynliga i AI. Åtgärda först för AI-trafik." },
  no: { title: "AI vs Google-gap", tagline: "Der Google rangerer deg men AI ignorerer deg.", visibilityGapReport: "Synlighetsgapsrapport", aiRisk: "AI-risiko", moderateGap: "Moderat gap", balanced: "Balansert", seoOpp: "SEO-mulighet", avgGapScore: "Snitt gap-poeng", totalQueries: "Totalt antall søk", topAiRiskQueries: "VIKTIGSTE AI-RISIKOSØK", bandSplit: "Båndfordeling", seoOpportunity: "SEO-mulighet", closing: "søk sterke på Google men usynlige i AI. Fiks først for AI-trafikk." },
  da: { title: "AI vs Google-gab", tagline: "Hvor Google rangerer dig men AI ignorerer dig.", visibilityGapReport: "Synlighedsgabsrapport", aiRisk: "AI-risiko", moderateGap: "Moderat gab", balanced: "Balanceret", seoOpp: "SEO-mulighed", avgGapScore: "Gns. gab-score", totalQueries: "Samlede forespørgsler", topAiRiskQueries: "VIGTIGSTE AI-RISIKOFORESPØRGSLER", bandSplit: "Båndfordeling", seoOpportunity: "SEO-mulighed", closing: "forespørgsler stærke på Google men usynlige i AI. Ret først for AI-trafik." },
  fi: { title: "Tekoäly vs Google -aukko", tagline: "Missä Google sijoittaa sinut mutta tekoäly ohittaa.", visibilityGapReport: "Näkyvyysaukkoraportti", aiRisk: "Tekoälyriski", moderateGap: "Kohtalainen aukko", balanced: "Tasapainoinen", seoOpp: "SEO-mahdollisuus", avgGapScore: "Keskim. aukkopisteet", totalQueries: "Hakut yhteensä", topAiRiskQueries: "TÄRKEIMMÄT TEKOÄLYRISKIH haut", bandSplit: "Kaistajako", seoOpportunity: "SEO-mahdollisuus", closing: "hakua vahvoja Googlessa mutta näkymättömiä tekoälyssä. Korjaa ensin tekoälyliikenteelle." },
};

// ── Geo Visibility translations ─────────────────────────────────────────────
const GEO_VISIBILITY: Record<VideoLangCode, GeoVisibilityStrings> = {
  en: { title: "Geo Visibility & Market Coverage", tagline: "Your geographic visibility footprint.", coverageReport: "Coverage Report", regionsAnalyzed: "Regions Analyzed", covered: "Covered", coverageGaps: "Coverage Gaps", avgVisibility: "Avg Visibility", topPerformingRegions: "TOP PERFORMING REGIONS", coverage: "Coverage", gaps: "Gaps", regionsCovered: "regions covered.", gapMarketsIdentified: "gap markets identified for expansion.", focusClosing: "Focus on closing coverage gaps to grow global reach." },
  es: { title: "Visibilidad Geo y Cobertura de Mercado", tagline: "Tu huella de visibilidad geográfica.", coverageReport: "Informe de Cobertura", regionsAnalyzed: "Regiones Analizadas", covered: "Cubiertas", coverageGaps: "Brechas de Cobertura", avgVisibility: "Visibilidad Promedio", topPerformingRegions: "REGIÓNES CON MEJOR RENDIMIENTO", coverage: "Cobertura", gaps: "Brechas", regionsCovered: "regiones cubiertas.", gapMarketsIdentified: "mercados con brechas identificados para expansión.", focusClosing: "Enfócate en cerrar brechas para crecer globalmente." },
  fr: { title: "Visibilité Géographique et Couverture Marché", tagline: "Votre empreinte de visibilité géographique.", coverageReport: "Rapport de Couverture", regionsAnalyzed: "Régions Analysées", covered: "Couvertes", coverageGaps: "Écarts de Couverture", avgVisibility: "Visibilité Moyenne", topPerformingRegions: "RÉGIONS LES PLUS PERFORMANTES", coverage: "Couverture", gaps: "Écarts", regionsCovered: "régions couvertes.", gapMarketsIdentified: "marchés à écarts identifiés pour expansion.", focusClosing: "Concentrez-vous sur la fermeture des écarts." },
  de: { title: "Geo-Sichtbarkeit & Marktabdeckung", tagline: "Ihr geografischer Sichtbarkeits-Fußabdruck.", coverageReport: "Abdeckungsbericht", regionsAnalyzed: "Analysierte Regionen", covered: "Abgedeckt", coverageGaps: "Abdeckungslücken", avgVisibility: "Ø Sichtbarkeit", topPerformingRegions: "TOP-REGIONEN", coverage: "Abdeckung", gaps: "Lücken", regionsCovered: "Regionen abgedeckt.", gapMarketsIdentified: "Lückenmärkte für Expansion identifiziert.", focusClosing: "Schließen Sie Lücken für globales Wachstum." },
  zh: { title: "地理可见性与市场覆盖", tagline: "您的地理可见性足迹。", coverageReport: "覆盖报告", regionsAnalyzed: "已分析地区", covered: "已覆盖", coverageGaps: "覆盖缺口", avgVisibility: "平均可见度", topPerformingRegions: "表现最佳地区", coverage: "覆盖", gaps: "缺口", regionsCovered: "个地区已覆盖。", gapMarketsIdentified: "个缺口市场已识别用于扩张。", focusClosing: "专注于缩小覆盖缺口以扩大全球覆盖。" },
  ja: { title: "地理的可視性と市場カバレッジ", tagline: "地理的な可視性フットプリント。", coverageReport: "カバレッジレポート", regionsAnalyzed: "分析地域", covered: "カバー済み", coverageGaps: "カバレッジギャップ", avgVisibility: "平均可視性", topPerformingRegions: "トップパフォーマンス地域", coverage: "カバレッジ", gaps: "ギャップ", regionsCovered: "地域をカバー。", gapMarketsIdentified: "拡張のためのギャップ市場を特定。", focusClosing: "カバレッジギャップを解消してグローバルリーチを拡大。" },
  pt: { title: "Visibilidade Geo e Cobertura de Mercado", tagline: "Sua pegada de visibilidade geográfica.", coverageReport: "Relatório de Cobertura", regionsAnalyzed: "Regiões Analisadas", covered: "Cobertas", coverageGaps: "Lacunas de Cobertura", avgVisibility: "Visibilidade Média", topPerformingRegions: "REGIÕES DE MELHOR DESEMPENHO", coverage: "Cobertura", gaps: "Lacunas", regionsCovered: "regiões cobertas.", gapMarketsIdentified: "mercados com lacunas identificados para expansão.", focusClosing: "Foque em fechar lacunas para crescer globalmente." },
  ar: { title: "الرؤية الجغرافية وتغطية السوق", tagline: "بصمتك الجغرافية للرؤية.", coverageReport: "تقرير التغطية", regionsAnalyzed: "المناطق المحللة", covered: "مغطاة", coverageGaps: "فجوات التغطية", avgVisibility: "متوسط الرؤية", topPerformingRegions: "المناطق الأفضل أداءً", coverage: "التغطية", gaps: "الفجوات", regionsCovered: "منطقة مغطاة.", gapMarketsIdentified: "أسواق فجوات محددة للتوسع.", focusClosing: "ركز على إغلاق الفجوات للنمو العالمي." },
  he: { title: "נראות גיאוגרפית וכיסוי שוק", tagline: "טביעת הרגל הגיאוגרפית שלך.", coverageReport: "דוח כיסוי", regionsAnalyzed: "אזורים שנותחו", covered: "מכוסים", coverageGaps: "פערי כיסוי", avgVisibility: "נראות ממוצעת", topPerformingRegions: "אזורים מובילים", coverage: "כיסוי", gaps: "פערים", regionsCovered: "אזורים מכוסים.", gapMarketsIdentified: "שווקי פער מזוהים להרחבה.", focusClosing: "התמקד בסגירת פערים לצמיחה גלובלית." },
  ru: { title: "Гео-видимость и охват рынка", tagline: "Ваш географический след видимости.", coverageReport: "Отчёт об охвате", regionsAnalyzed: "Проанализировано регионов", covered: "Покрыто", coverageGaps: "Пробелы охвата", avgVisibility: "Средняя видимость", topPerformingRegions: "ТОП-РЕГИОНЫ", coverage: "Охват", gaps: "Пробелы", regionsCovered: "регионов покрыто.", gapMarketsIdentified: "выявлены рынки с пробелами для расширения.", focusClosing: "Закройте пробелы для глобального роста." },
  it: { title: "Visibilità Geo e Copertura Mercato", tagline: "La tua impronta di visibilità geografica.", coverageReport: "Rapporto Copertura", regionsAnalyzed: "Regioni Analizzate", covered: "Coperte", coverageGaps: "Lacune di Copertura", avgVisibility: "Visibilità Media", topPerformingRegions: "REGIÓNI MIGLIORI", coverage: "Copertura", gaps: "Lacune", regionsCovered: "regioni coperte.", gapMarketsIdentified: "mercati con lacune identificati per espansione.", focusClosing: "Concentrati sulla chiusura delle lacune." },
  nl: { title: "Geo-zichtbaarheid & Marktdekking", tagline: "Uw geografische zichtbaarheidsvoetafdruk.", coverageReport: "Dekkingsrapport", regionsAnalyzed: "Geanalyseerde regio's", covered: "Gedekt", coverageGaps: "Dekkingshiaten", avgVisibility: "Gem. zichtbaarheid", topPerformingRegions: "TOP-REGIO'S", coverage: "Dekking", gaps: "Hiaten", regionsCovered: "regio's gedekt.", gapMarketsIdentified: "hiatenmarkten geïdentificeerd voor uitbreiding.", focusClosing: "Focus op het sluiten van hiaten." },
  pl: { title: "Widoczność Geo i Pokrycie Rynku", tagline: "Twój geograficzny ślad widoczności.", coverageReport: "Raport Pokrycia", regionsAnalyzed: "Przeanalizowane regiony", covered: "Pokryte", coverageGaps: "Luki pokrycia", avgVisibility: "Śr. widoczność", topPerformingRegions: "NAJLEPSZE REGIONY", coverage: "Pokrycie", gaps: "Luki", regionsCovered: "regionów pokrytych.", gapMarketsIdentified: "rynki z lukami zidentyfikowane do ekspansji.", focusClosing: "Skup się na zamykaniu luk." },
  ko: { title: "지리적 가시성 및 시장 커버리지", tagline: "지리적 가시성 발자국.", coverageReport: "커버리지 보고서", regionsAnalyzed: "분석된 지역", covered: "커버됨", coverageGaps: "커버리지 갭", avgVisibility: "평균 가시성", topPerformingRegions: "최고 성과 지역", coverage: "커버리지", gaps: "갭", regionsCovered: "개 지역 커버됨.", gapMarketsIdentified: "확장을 위한 갭 시장 식별.", focusClosing: "갭 해소에 집중하여 글로벌 도달 확대." },
  tr: { title: "Coğrafi Görünürlük ve Pazar Kapsamı", tagline: "Coğrafi görünürlük ayak iziniz.", coverageReport: "Kapsam Raporu", regionsAnalyzed: "Analiz Edilen Bölgeler", covered: "Kapsanmış", coverageGaps: "Kapsam Boşlukları", avgVisibility: "Ort. Görünürlük", topPerformingRegions: "EN İYİ BÖLGELER", coverage: "Kapsam", gaps: "Boşluklar", regionsCovered: "bölge kapsandı.", gapMarketsIdentified: "genişleme için boşluk pazarları belirlendi.", focusClosing: "Küresel erişim için boşlukları kapatın." },
  hi: { title: "जियो विज़िबिलिटी और मार्केट कवरेज", tagline: "आपकी भौगोलिक विज़िबिलिटी पदचिह्न।", coverageReport: "कवरेज रिपोर्ट", regionsAnalyzed: "विश्लेषित क्षेत्र", covered: "कवर", coverageGaps: "कवरेज अंतराल", avgVisibility: "औसत विज़िबिलिटी", topPerformingRegions: "शीर्ष प्रदर्शन क्षेत्र", coverage: "कवरेज", gaps: "अंतराल", regionsCovered: "क्षेत्र कवर।", gapMarketsIdentified: "विस्तार के लिए अंतराल बाजार पहचाने।", focusClosing: "कवरेज अंतराल बंद करने पर ध्यान दें।" },
  th: { title: "การมองเห็นทางภูมิศาสตร์และความครอบคลุมตลาด", tagline: "รอยเท้าความมองเห็นทางภูมิศาสตร์ของคุณ", coverageReport: "รายงานความครอบคลุม", regionsAnalyzed: "ภูมิภาคที่วิเคราะห์", covered: "ครอบคลุม", coverageGaps: "ช่องว่างความครอบคลุม", avgVisibility: "การมองเห็นเฉลี่ย", topPerformingRegions: "ภูมิภาคที่มีประสิทธิภาพสูงสุด", coverage: "ความครอบคลุม", gaps: "ช่องว่าง", regionsCovered: "ภูมิภาคครอบคลุม", gapMarketsIdentified: "ระบุตลาดช่องว่างสำหรับการขยายตัว", focusClosing: "มุ่งเน้นที่การปิดช่องว่างเพื่อขยายการเข้าถึงทั่วโลก" },
  vi: { title: "Khả Năng Hiển thị Địa lý & Phủ Sóng Thị trường", tagline: "Dấu chân hiển thị địa lý của bạn.", coverageReport: "Báo cáo Phủ sóng", regionsAnalyzed: "Khu vực Đã phân tích", covered: "Đã phủ", coverageGaps: "Khoảng trống Phủ sóng", avgVisibility: "Hiển thị TB", topPerformingRegions: "KHU VỰC HOẠT ĐỘNG TỐT NHẤT", coverage: "Phủ sóng", gaps: "Khoảng trống", regionsCovered: "khu vực đã phủ.", gapMarketsIdentified: "thị trường khoảng trống xác định để mở rộng.", focusClosing: "Tập trung đóng khoảng trống để mở rộng toàn cầu." },
  id: { title: "Visibilitas Geo & Cakupan Pasar", tagline: "Jejak visibilitas geografis Anda.", coverageReport: "Laporan Cakupan", regionsAnalyzed: "Wilayah Dianalisis", covered: "Tercakup", coverageGaps: "Kesenjangan Cakupan", avgVisibility: "Visibilitas Rata-rata", topPerformingRegions: "WILAYAH TERBAIK", coverage: "Cakupan", gaps: "Kesenjangan", regionsCovered: "wilayah tercakup.", gapMarketsIdentified: "pasar kesenjangan diidentifikasi untuk ekspansi.", focusClosing: "Fokus tutup kesenjangan untuk pertumbuhan global." },
  sv: { title: "Geo-synlighet & Marknadstäckning", tagline: "Din geografiska synlighetsfotavtryck.", coverageReport: "Täckningsrapport", regionsAnalyzed: "Analyserade regioner", covered: "Täckt", coverageGaps: "Täckningsluckor", avgVisibility: "Snitt synlighet", topPerformingRegions: "BÄSTA REGIONER", coverage: "Täckning", gaps: "Luckor", regionsCovered: "regioner täckta.", gapMarketsIdentified: "luckormarknader identifierade för expansion.", focusClosing: "Fokusera på att stänga luckor." },
  no: { title: "Geo-synlighet & Markedsdekning", tagline: "Ditt geografiske synlighetsfotavtrykk.", coverageReport: "Dekningsrapport", regionsAnalyzed: "Analyserte regioner", covered: "Dekket", coverageGaps: "Dekningshull", avgVisibility: "Snitt synlighet", topPerformingRegions: "BESTE REGIONER", coverage: "Dekning", gaps: "Hull", regionsCovered: "regioner dekket.", gapMarketsIdentified: "hullmarkeder identifisert for ekspansjon.", focusClosing: "Fokuser på å lukke hull." },
  da: { title: "Geo-synlighed & Markedsdækning", tagline: "Dit geografiske synlighedsfodaftryk.", coverageReport: "Dækningsrapport", regionsAnalyzed: "Analyserede regioner", covered: "Dækket", coverageGaps: "Dækningshuller", avgVisibility: "Gns. synlighed", topPerformingRegions: "BEDSTE REGIONER", coverage: "Dækning", gaps: "Huller", regionsCovered: "regioner dækket.", gapMarketsIdentified: "hullermarkeder identificeret til udvidelse.", focusClosing: "Fokusér på at lukke huller." },
  fi: { title: "Maantieteellinen näkyvyys ja markkinakattavuus", tagline: "Maantieteellinen näkyvyysjälkesi.", coverageReport: "Kattavuusraportti", regionsAnalyzed: "Analysoidut alueet", covered: "Katettu", coverageGaps: "Kattavuusaukot", avgVisibility: "Keskim. näkyvyys", topPerformingRegions: "PARHAAT ALUEET", coverage: "Kattavuus", gaps: "Aukot", regionsCovered: "aluetta katettu.", gapMarketsIdentified: "aukkomarkkinat tunnistettu laajentumiseen.", focusClosing: "Sulje aukot globaaliin kasvuun." },
};

// ── Global Visibility Matrix translations ────────────────────────────────────
const GLOBAL_VISIBILITY: Record<VideoLangCode, GlobalVisibilityStrings> = {
  en: { title: "Global Visibility Matrix", tagline: "Where does the world see you?", globalCoverage: "Global Coverage", strong: "Strong", emerging: "Emerging", declining: "Declining", absent: "Absent", countriesAnalyzed: "countries analyzed", avgScore: "Avg Score", topOpportunities: "Top Opportunities", absentMarkets: "Absent Markets", closing: "markets with zero visibility — major expansion opportunity." },
  es: { title: "Matriz de Visibilidad Global", tagline: "¿Dónde te ve el mundo?", globalCoverage: "Cobertura Global", strong: "Fuerte", emerging: "Emergente", declining: "En Declive", absent: "Ausente", countriesAnalyzed: "países analizados", avgScore: "Puntuación Media", topOpportunities: "Principales Oportunidades", absentMarkets: "Mercados Ausentes", closing: "mercados fuertes, emergentes. mercados con cero visibilidad — gran oportunidad de expansión." },
  fr: { title: "Matrice de Visibilité Mondiale", tagline: "Où le monde vous voit-il ?", globalCoverage: "Couverture Mondiale", strong: "Fort", emerging: "Émergent", declining: "En Déclin", absent: "Absent", countriesAnalyzed: "pays analysés", avgScore: "Score Moyen", topOpportunities: "Principales Opportunités", absentMarkets: "Marchés Absents", closing: "marchés forts, émergents. marchés à visibilité zéro — grande opportunité d'expansion." },
  de: { title: "Globale Sichtbarkeitsmatrix", tagline: "Wo sieht die Welt Sie?", globalCoverage: "Globale Abdeckung", strong: "Stark", emerging: "Aufstrebend", declining: "Rückläufig", absent: "Abwesend", countriesAnalyzed: "Länder analysiert", avgScore: "Ø Score", topOpportunities: "Top-Chancen", absentMarkets: "Abwesende Märkte", closing: "starke Märkte, aufstrebend. Märkte mit Null-Sichtbarkeit — große Expansionschance." },
  zh: { title: "全球可见性矩阵", tagline: "世界在哪里看到你？", globalCoverage: "全球覆盖", strong: "强势", emerging: "新兴", declining: "衰退", absent: "缺席", countriesAnalyzed: "个国家已分析", avgScore: "平均得分", topOpportunities: "主要机会", absentMarkets: "缺席市场", closing: "个强势市场，新兴。零可见性市场—重大扩张机会。" },
  ja: { title: "グローバル可視性マトリックス", tagline: "世界はどこであなたを見ていますか？", globalCoverage: "グローバルカバレッジ", strong: "強い", emerging: "新興", declining: "衰退", absent: "不在", countriesAnalyzed: "カ国分析済み", avgScore: "平均スコア", topOpportunities: "主要機会", absentMarkets: "不在市場", closing: "強市場、新興。ゼロ可視性市場—大きな拡張機会。" },
  pt: { title: "Matriz de Visibilidade Global", tagline: "Onde o mundo te vê?", globalCoverage: "Cobertura Global", strong: "Forte", emerging: "Emergente", declining: "Em Declínio", absent: "Ausente", countriesAnalyzed: "países analisados", avgScore: "Pontuação Média", topOpportunities: "Principais Oportunidades", absentMarkets: "Mercados Ausentes", closing: "mercados fortes, emergentes. mercados com zero visibilidade — grande oportunidade de expansão." },
  ar: { title: "مصفوفة الرؤية العالمية", tagline: "أين يراك العالم؟", globalCoverage: "التغطية العالمية", strong: "قوي", emerging: "ناشئ", declining: "متراجع", absent: "غائب", countriesAnalyzed: "دولة محللة", avgScore: "متوسط الدرجة", topOpportunities: "أهم الفرص", absentMarkets: "أسواق غائبة", closing: "أسواق قوية، ناشئة. أسواق بصفر رؤية — فرصة توسع كبرى." },
  he: { title: "מטריצת נראות גלובלית", tagline: "איפה העולם רואה אותך?", globalCoverage: "כיסוי גלובלי", strong: "חזק", emerging: "מתעורר", declining: "יורד", absent: "חסר", countriesAnalyzed: "מדינות נותחו", avgScore: "ציון ממוצע", topOpportunities: "הזדמנויות עיקריות", absentMarkets: "שווקים חסרים", closing: "שווקים חזקים, מתעוררים. שווקים עם אפס נראות — הזדמנות הרחבה מרכזית." },
  ru: { title: "Глобальная матрица видимости", tagline: "Где мир вас видит?", globalCoverage: "Глобальное покрытие", strong: "Сильные", emerging: "Развивающиеся", declining: "Снижающиеся", absent: "Отсутствующие", countriesAnalyzed: "стран проанализировано", avgScore: "Средний балл", topOpportunities: "Топ-возможности", absentMarkets: "Отсутствующие рынки", closing: "сильных рынков, развивающихся. рынков с нулевой видимостью — крупная возможность расширения." },
  it: { title: "Matrice di Visibilità Globale", tagline: "Dove ti vede il mondo?", globalCoverage: "Copertura Globale", strong: "Forte", emerging: "Emergente", declining: "In Declino", absent: "Assente", countriesAnalyzed: "paesi analizzati", avgScore: "Punteggio Medio", topOpportunities: "Principali Opportunità", absentMarkets: "Mercati Assenti", closing: "mercati forti, emergenti. mercati a visibilità zero — grande opportunità di espansione." },
  nl: { title: "Globale Zichtbaarheidsmatrix", tagline: "Waar ziet de wereld jou?", globalCoverage: "Globale Dekking", strong: "Sterk", emerging: "Opkomend", declining: "Dalend", absent: "Afwezig", countriesAnalyzed: "landen geanalyseerd", avgScore: "Gem. score", topOpportunities: "Topkansen", absentMarkets: "Afwezige Markten", closing: "sterke markten, opkomend. markten met nul zichtbaarheid — grote expansiekans." },
  pl: { title: "Globalna Macierz Widoczności", tagline: "Gdzie świat Cię widzi?", globalCoverage: "Globalne Pokrycie", strong: "Silny", emerging: "Wschodzący", declining: "Spadający", absent: "Nieobecny", countriesAnalyzed: "krajów przeanalizowano", avgScore: "Śr. wynik", topOpportunities: "Główne Szanse", absentMarkets: "Nieobecne Rynki", closing: "silnych rynków, wschodzących. rynków z zerową widocznością — duża szansa ekspansji." },
  ko: { title: "글로벌 가시성 매트릭스", tagline: "세상이 당신을 어디서 봅니까?", globalCoverage: "글로벌 커버리지", strong: "강함", emerging: "신흥", declining: "감소", absent: "부재", countriesAnalyzed: "개국 분석됨", avgScore: "평균 점수", topOpportunities: "주요 기회", absentMarkets: "부재 시장", closing: "개 강한 시장, 신흥. 제로 가시성 시장—주요 확장 기회." },
  tr: { title: "Küresel Görünürlük Matrisi", tagline: "Dünya sizi nerede görüyor?", globalCoverage: "Küresel Kapsam", strong: "Güçlü", emerging: "Yükselen", declining: "Düşen", absent: "Yok", countriesAnalyzed: "ülke analiz edildi", avgScore: "Ort. puan", topOpportunities: "Önemli Fırsatlar", absentMarkets: "Yok Pazarlar", closing: "güçlü pazar, yükselen. sıfır görünürlüklü pazarlar — büyük genişleme fırsatı." },
  hi: { title: "ग्लोबल विज़िबिलिटी मैट्रिक्स", tagline: "दुनिया आपको कहाँ देखती है?", globalCoverage: "ग्लोबल कवरेज", strong: "मजबूत", emerging: "उभरता", declining: "गिरता", absent: "अनुपस्थित", countriesAnalyzed: "देश विश्लेषित", avgScore: "औसत स्कोर", topOpportunities: "शीर्ष अवसर", absentMarkets: "अनुपस्थित बाजार", closing: "मजबूत बाजार, उभरते। शून्य विज़िबिलिटी बाजार—प्रमुख विस्तार अवसर।" },
  th: { title: "เมทริกซ์การมองเห็นทั่วโลก", tagline: "โลกมองเห็นคุณที่ไหน?", globalCoverage: "ความครอบคลุมทั่วโลก", strong: "แข็งแกร่ง", emerging: "กำลังเติบโต", declining: "ลดลง", absent: "ไม่มี", countriesAnalyzed: "ประเทศที่วิเคราะห์", avgScore: "คะแนนเฉลี่ย", topOpportunities: "โอกาสหลัก", absentMarkets: "ตลาดที่ไม่มี", closing: "ตลาดแข็งแกร่ง กำลังเติบโต ตลาดที่มองไม่เห็น—โอกาสขยายตัวสำคัญ" },
  vi: { title: "Ma trận Hiển thị Toàn cầu", tagline: "Thế giới thấy bạn ở đâu?", globalCoverage: "Phủ sóng Toàn cầu", strong: "Mạnh", emerging: "Đang nổi", declining: "Suy giảm", absent: "Vắng mặt", countriesAnalyzed: "quốc gia đã phân tích", avgScore: "Điểm TB", topOpportunities: "Cơ hội Chính", absentMarkets: "Thị trường Vắng mặt", closing: "thị trường mạnh, đang nổi. thị trường không hiển thị — cơ hội mở rộng lớn." },
  id: { title: "Matriks Visibilitas Global", tagline: "Di mana dunia melihat Anda?", globalCoverage: "Cakupan Global", strong: "Kuat", emerging: "Meningkat", declining: "Menurun", absent: "Tidak ada", countriesAnalyzed: "negara dianalisis", avgScore: "Skor Rata-rata", topOpportunities: "Peluang Utama", absentMarkets: "Pasar Tidak Ada", closing: "pasar kuat, meningkat. pasar dengan visibilitas nol — peluang ekspansi besar." },
  sv: { title: "Global synlighetsmatris", tagline: "Var ser världen dig?", globalCoverage: "Global täckning", strong: "Stark", emerging: "Växande", declining: "Minskande", absent: "Frånvarande", countriesAnalyzed: "länder analyserade", avgScore: "Snittpoäng", topOpportunities: "Toppmöjligheter", absentMarkets: "Frånvarande marknader", closing: "starka marknader, växande. marknader med noll synlighet — stor expansionsmöjlighet." },
  no: { title: "Global synlighetsmatrise", tagline: "Hvor ser verden deg?", globalCoverage: "Global dekning", strong: "Sterk", emerging: "Voksende", declining: "Synkende", absent: "Fraværende", countriesAnalyzed: "land analysert", avgScore: "Snittpoeng", topOpportunities: "Toppmuligheter", absentMarkets: "Fraværende markeder", closing: "sterke markeder, voksende. markeder med null synlighet — stor ekspansjonsmulighet." },
  da: { title: "Global synlighedsmatrix", tagline: "Hvor ser verden dig?", globalCoverage: "Global dækning", strong: "Stærk", emerging: "Voksende", declining: "Faldende", absent: "Fraværende", countriesAnalyzed: "lande analyseret", avgScore: "Gns. score", topOpportunities: "Topmuligheder", absentMarkets: "Fraværende markeder", closing: "stærke markeder, voksende. markeder med nul synlighed — stor ekspansionsmulighed." },
  fi: { title: "Globaali näkyvyysmatriisi", tagline: "Mistä maailma näkee sinut?", globalCoverage: "Globaali kattavuus", strong: "Vahva", emerging: "Nouseva", declining: "Laskeva", absent: "Poissa", countriesAnalyzed: "maata analysoitu", avgScore: "Keskim. pisteet", topOpportunities: "Tärkeimmät mahdollisuudet", absentMarkets: "Poissa olevat markkinat", closing: "vahvaa markkinaa, nouseva. markkinoita nolla näkyvyydellä — suuri laajennusmahdollisuus." },
};

// ── Global Visibility Matrix (Google Search tab) ───────────────────────────────
const GLOBAL_VISIBILITY_GOOGLE: Record<VideoLangCode, GlobalVisibilityGoogleStrings> = {
  en: { title: "Region vs Google Search", tagline: "Google Search Console performance by region.", googleSearchReport: "Google Search Report", totalClicks: "Total Clicks", totalImpressions: "Total Impressions", avgCtr: "Avg CTR", regionsAnalyzed: "regions analyzed", topByClicks: "Top by Clicks", topByImpressions: "Top by Impressions", closing: "regions with Google Search data. Optimize underperforming regions." },
  es: { title: "Región vs Búsqueda Google", tagline: "Rendimiento de Search Console por región.", googleSearchReport: "Informe Búsqueda Google", totalClicks: "Clics Totales", totalImpressions: "Impresiones Totales", avgCtr: "CTR Promedio", regionsAnalyzed: "regiones analizadas", topByClicks: "Top por Clics", topByImpressions: "Top por Impresiones", closing: "regiones con datos de Google Search. Optimiza regiones con bajo rendimiento." },
  fr: { title: "Région vs Recherche Google", tagline: "Performances Search Console par région.", googleSearchReport: "Rapport Recherche Google", totalClicks: "Clics Totaux", totalImpressions: "Impressions Totales", avgCtr: "CTR Moyen", regionsAnalyzed: "régions analysées", topByClicks: "Top par Clics", topByImpressions: "Top par Impressions", closing: "régions avec données Google Search. Optimisez les régions sous-performantes." },
  de: { title: "Region vs Google-Suche", tagline: "Search-Console-Performance nach Region.", googleSearchReport: "Google-Suchbericht", totalClicks: "Klicks Gesamt", totalImpressions: "Impressionen Gesamt", avgCtr: "Ø CTR", regionsAnalyzed: "Regionen analysiert", topByClicks: "Top nach Klicks", topByImpressions: "Top nach Impressionen", closing: "Regionen mit Google-Suchdaten. Unterperformende Regionen optimieren." },
  zh: { title: "地区 vs 谷歌搜索", tagline: "按地区的搜索控制台表现。", googleSearchReport: "谷歌搜索报告", totalClicks: "总点击", totalImpressions: "总展示", avgCtr: "平均CTR", regionsAnalyzed: "个地区已分析", topByClicks: "按点击排名", topByImpressions: "按展示排名", closing: "个地区有谷歌搜索数据。优化表现不佳的地区。" },
  ja: { title: "地域 vs Google検索", tagline: "地域別Search Consoleパフォーマンス。", googleSearchReport: "Google検索レポート", totalClicks: "総クリック", totalImpressions: "総インプレッション", avgCtr: "平均CTR", regionsAnalyzed: "地域分析済み", topByClicks: "クリック順", topByImpressions: "インプレッション順", closing: "地域にGoogle検索データ。低パフォーマンス地域を最適化。" },
  pt: { title: "Região vs Pesquisa Google", tagline: "Desempenho Search Console por região.", googleSearchReport: "Relatório Pesquisa Google", totalClicks: "Cliques Totais", totalImpressions: "Impressões Totais", avgCtr: "CTR Médio", regionsAnalyzed: "regiões analisadas", topByClicks: "Top por Cliques", topByImpressions: "Top por Impressões", closing: "regiões com dados Google Search. Otimize regiões com baixo desempenho." },
  ar: { title: "المنطقة مقابل بحث جوجل", tagline: "أداء Search Console حسب المنطقة.", googleSearchReport: "تقرير بحث جوجل", totalClicks: "إجمالي النقرات", totalImpressions: "إجمالي مرات الظهور", avgCtr: "متوسط CTR", regionsAnalyzed: "منطقة محللة", topByClicks: "الأعلى بالنقرات", topByImpressions: "الأعلى بمرات الظهور", closing: "منطقة ببيانات بحث جوجل. حسّن المناطق ذات الأداء المنخفض." },
  he: { title: "אזור מול חיפוש Google", tagline: "ביצועי Search Console לפי אזור.", googleSearchReport: "דוח חיפוש Google", totalClicks: "סה״כ קליקים", totalImpressions: "סה״כ חשיפות", avgCtr: "CTR ממוצע", regionsAnalyzed: "אזורים נותחו", topByClicks: "מובילים בקליקים", topByImpressions: "מובילים בחשיפות", closing: "אזורים עם נתוני חיפוש Google. אופטם אזורים חלשים." },
  ru: { title: "Регион vs Поиск Google", tagline: "Показатели Search Console по регионам.", googleSearchReport: "Отчёт Google Поиск", totalClicks: "Всего кликов", totalImpressions: "Всего показов", avgCtr: "Средний CTR", regionsAnalyzed: "регионов проанализировано", topByClicks: "Топ по кликам", topByImpressions: "Топ по показам", closing: "регионов с данными Google. Оптимизируйте слабые регионы." },
  it: { title: "Regione vs Ricerca Google", tagline: "Prestazioni Search Console per regione.", googleSearchReport: "Rapporto Ricerca Google", totalClicks: "Clic Totali", totalImpressions: "Impressioni Totali", avgCtr: "CTR Medio", regionsAnalyzed: "regioni analizzate", topByClicks: "Top per Clic", topByImpressions: "Top per Impressioni", closing: "regioni con dati Google Search. Ottimizza regioni sottoperformanti." },
  nl: { title: "Regio vs Google Zoeken", tagline: "Search Console-prestaties per regio.", googleSearchReport: "Google Zoekrapport", totalClicks: "Totaal Klikken", totalImpressions: "Totaal Impressies", avgCtr: "Gem. CTR", regionsAnalyzed: "regio's geanalyseerd", topByClicks: "Top op Klikken", topByImpressions: "Top op Impressies", closing: "regio's met Google Zoekdata. Optimaliseer onderpresterende regio's." },
  pl: { title: "Region vs Wyszukiwarka Google", tagline: "Wyniki Search Console według regionu.", googleSearchReport: "Raport Wyszukiwarki Google", totalClicks: "Łączne Kliknięcia", totalImpressions: "Łączne Wyświetlenia", avgCtr: "Śr. CTR", regionsAnalyzed: "regionów przeanalizowano", topByClicks: "Top według Kliknięć", topByImpressions: "Top według Wyświetleń", closing: "regionów z danymi Google. Optymalizuj słabsze regiony." },
  ko: { title: "지역 vs Google 검색", tagline: "지역별 Search Console 성과.", googleSearchReport: "Google 검색 보고서", totalClicks: "총 클릭", totalImpressions: "총 노출", avgCtr: "평균 CTR", regionsAnalyzed: "개 지역 분석됨", topByClicks: "클릭 순위", topByImpressions: "노출 순위", closing: "개 지역에 Google 검색 데이터. 저성과 지역 최적화." },
  tr: { title: "Bölge vs Google Arama", tagline: "Bölgeye göre Search Console performansı.", googleSearchReport: "Google Arama Raporu", totalClicks: "Toplam Tıklama", totalImpressions: "Toplam Görüntülenme", avgCtr: "Ort. CTR", regionsAnalyzed: "bölge analiz edildi", topByClicks: "Tıklamaya Göre Top", topByImpressions: "Görüntülenmeye Göre Top", closing: "bölgede Google Arama verisi. Düşük performanslı bölgeleri optimize edin." },
  hi: { title: "क्षेत्र बनाम Google खोज", tagline: "क्षेत्र के अनुसार Search Console प्रदर्शन।", googleSearchReport: "Google खोज रिपोर्ट", totalClicks: "कुल क्लिक", totalImpressions: "कुल इंप्रेशन", avgCtr: "औसत CTR", regionsAnalyzed: "क्षेत्र विश्लेषित", topByClicks: "क्लिक के अनुसार शीर्ष", topByImpressions: "इंप्रेशन के अनुसार शीर्ष", closing: "क्षेत्रों में Google खोज डेटा। कम प्रदर्शन वाले क्षेत्रों को अनुकूलित करें।" },
  th: { title: "ภูมิภาค เทียบกับ Google Search", tagline: "ประสิทธิภาพ Search Console ตามภูมิภาค", googleSearchReport: "รายงาน Google Search", totalClicks: "คลิกทั้งหมด", totalImpressions: "การแสดงผลทั้งหมด", avgCtr: "CTR เฉลี่ย", regionsAnalyzed: "ภูมิภาคที่วิเคราะห์", topByClicks: "อันดับตามคลิก", topByImpressions: "อันดับตามการแสดงผล", closing: "ภูมิภาคที่มีข้อมูล Google Search ปรับปรุงภูมิภาคที่ทำงานได้ไม่ดี" },
  vi: { title: "Khu vực vs Google Tìm kiếm", tagline: "Hiệu suất Search Console theo khu vực.", googleSearchReport: "Báo cáo Google Tìm kiếm", totalClicks: "Tổng Nhấp chuột", totalImpressions: "Tổng Hiển thị", avgCtr: "CTR TB", regionsAnalyzed: "khu vực đã phân tích", topByClicks: "Top theo Nhấp chuột", topByImpressions: "Top theo Hiển thị", closing: "khu vực có dữ liệu Google. Tối ưu khu vực kém hiệu suất." },
  id: { title: "Wilayah vs Pencarian Google", tagline: "Kinerja Search Console per wilayah.", googleSearchReport: "Laporan Pencarian Google", totalClicks: "Total Klik", totalImpressions: "Total Tampilan", avgCtr: "CTR Rata-rata", regionsAnalyzed: "wilayah dianalisis", topByClicks: "Top menurut Klik", topByImpressions: "Top menurut Tampilan", closing: "wilayah dengan data Google Search. Optimalkan wilayah berkinerja rendah." },
  sv: { title: "Region vs Google-sökning", tagline: "Search Console-prestanda per region.", googleSearchReport: "Google-sökrapport", totalClicks: "Totalt Klick", totalImpressions: "Totalt Visningar", avgCtr: "Snitt CTR", regionsAnalyzed: "regioner analyserade", topByClicks: "Top efter Klick", topByImpressions: "Top efter Visningar", closing: "regioner med Google-sökdata. Optimera underpresterande regioner." },
  no: { title: "Region vs Google-søk", tagline: "Search Console-ytelse per region.", googleSearchReport: "Google-søkerapport", totalClicks: "Totalt Klikk", totalImpressions: "Totalt Visninger", avgCtr: "Snitt CTR", regionsAnalyzed: "regioner analysert", topByClicks: "Topp etter Klikk", topByImpressions: "Topp etter Visninger", closing: "regioner med Google-søkedata. Optimaliser underpresterende regioner." },
  da: { title: "Region vs Google-søgning", tagline: "Search Console-præstation per region.", googleSearchReport: "Google-søgerapport", totalClicks: "Totalt Klik", totalImpressions: "Totalt Visninger", avgCtr: "Gns. CTR", regionsAnalyzed: "regioner analyseret", topByClicks: "Top efter Klik", topByImpressions: "Top efter Visninger", closing: "regioner med Google-søgedata. Optimer underpræsterende regioner." },
  fi: { title: "Alue vs Google-haku", tagline: "Search Console -suorituskyky alueittain.", googleSearchReport: "Google-hakuraportti", totalClicks: "Klikkaukset yhteensä", totalImpressions: "Näyttökerrat yhteensä", avgCtr: "Keskim. CTR", regionsAnalyzed: "aluetta analysoitu", topByClicks: "Top klikkauksilla", topByImpressions: "Top näyttökerroilla", closing: "aluetta Google-hakudatalla. Optimoi heikosti suoriutuvat alueet." },
  ur: { title: "علاقہ بمقابلہ گوگل سرچ", tagline: "علاقے کے لحاظ سے Search Console کارکردگی۔", googleSearchReport: "گوگل سرچ رپورٹ", totalClicks: "کل کلکس", totalImpressions: "کل تاثرات", avgCtr: "اوسط CTR", regionsAnalyzed: "علاقے تجزیہ شدہ", topByClicks: "کلکس کے لحاظ سے ٹاپ", topByImpressions: "تاثرات کے لحاظ سے ٹاپ", closing: "علاقوں میں گوگل سرچ ڈیٹا۔ کم کارکردگی والے علاقوں کو بہتر بنائیں۔" },
};

// Helper: get lang code and strings; for unsupported langs, return en + instruction
export function getOppBlindSpotsStrings(langCode: string): { s: OppBlindSpotsStrings; useInstruction: boolean } {
  const code = (langCode || "en").toLowerCase().split("-")[0] as VideoLangCode;
  const s = OPP_BLIND_SPOTS[code] || OPP_BLIND_SPOTS.en;
  return { s, useInstruction: !OPP_BLIND_SPOTS[code] };
}

export function getMarketShareStrings(langCode: string): { s: MarketShareStrings; useInstruction: boolean } {
  const code = (langCode || "en").toLowerCase().split("-")[0] as VideoLangCode;
  const s = MARKET_SHARE[code] || MARKET_SHARE.en;
  return { s, useInstruction: !MARKET_SHARE[code] };
}

export function getStrategicBlindSpotsStrings(langCode: string): { s: StrategicBlindSpotsStrings; useInstruction: boolean } {
  const code = (langCode || "en").toLowerCase().split("-")[0] as VideoLangCode;
  const s = STRATEGIC_BLIND_SPOTS[code] || STRATEGIC_BLIND_SPOTS.en;
  return { s, useInstruction: !STRATEGIC_BLIND_SPOTS[code] };
}

export function getAiSearchPresenceStrings(langCode: string): { s: AiSearchPresenceStrings; useInstruction: boolean } {
  const code = (langCode || "en").toLowerCase().split("-")[0] as VideoLangCode;
  const s = AI_SEARCH_PRESENCE[code] || AI_SEARCH_PRESENCE.en;
  return { s, useInstruction: !AI_SEARCH_PRESENCE[code] };
}

export function getAiVsGoogleGapStrings(langCode: string): { s: AiVsGoogleGapStrings; useInstruction: boolean } {
  const code = (langCode || "en").toLowerCase().split("-")[0] as VideoLangCode;
  const s = AI_VS_GOOGLE_GAP[code] || AI_VS_GOOGLE_GAP.en;
  return { s, useInstruction: !AI_VS_GOOGLE_GAP[code] };
}

export function getGeoVisibilityStrings(langCode: string): { s: GeoVisibilityStrings; useInstruction: boolean } {
  const code = (langCode || "en").toLowerCase().split("-")[0] as VideoLangCode;
  const s = GEO_VISIBILITY[code] || GEO_VISIBILITY.en;
  return { s, useInstruction: !GEO_VISIBILITY[code] };
}

export function getGlobalVisibilityStrings(langCode: string): { s: GlobalVisibilityStrings; useInstruction: boolean } {
  const code = (langCode || "en").toLowerCase().split("-")[0] as VideoLangCode;
  const s = GLOBAL_VISIBILITY[code] || GLOBAL_VISIBILITY.en;
  return { s, useInstruction: !GLOBAL_VISIBILITY[code] };
}

export function getGlobalVisibilityGoogleStrings(langCode: string): { s: GlobalVisibilityGoogleStrings; useInstruction: boolean } {
  const code = (langCode || "en").toLowerCase().split("-")[0] as VideoLangCode;
  const s = GLOBAL_VISIBILITY_GOOGLE[code] || GLOBAL_VISIBILITY_GOOGLE.en;
  return { s, useInstruction: !GLOBAL_VISIBILITY_GOOGLE[code] };
}

// For reports without full translation maps yet, use instruction-based approach
export function getLangInstruction(langCode: string): string {
  const code = (langCode || "en").toLowerCase().split("-")[0];
  if (code === "en") return "";
  const langName = LANGUAGE_NAMES[code] || LANGUAGE_NAMES[langCode] || "English";
  return `OUTPUT LANGUAGE: ${langName}. MANDATORY: Generate ALL on-screen text, titles, labels, numbers, charts, and written content in ${langName} only. Translate every English phrase in this prompt to ${langName} for display. No English text on screen.\n\n`;
}
